package pe.gob.huata.ecolactea.server.finance

import com.zaxxer.hikari.HikariDataSource
import io.ktor.http.*
import io.ktor.server.application.*
import io.ktor.server.request.receive
import io.ktor.server.response.respond
import io.ktor.server.routing.*
import kotlinx.coroutines.Dispatchers
import kotlinx.coroutines.withContext
import pe.gob.huata.ecolactea.core.application.AppResult
import pe.gob.huata.ecolactea.core.model.*
import pe.gob.huata.ecolactea.core.network.*
import pe.gob.huata.ecolactea.server.BusinessCalendar
import pe.gob.huata.ecolactea.server.auth.AuthService
import java.math.BigDecimal
import java.math.RoundingMode
import java.sql.*
import java.time.Instant
import java.time.LocalDate
import java.util.UUID

fun Route.financeRoutes(dataSource:HikariDataSource?,auth:AuthService?){route("/api/v1"){
    post("/weekly-closures"){val request=call.receive<WeeklyClosureCommand>();secured(auth,call,Permission.MANAGE_SETTLEMENTS){user->database(dataSource,call){it.closeWeek(request,user)}}}
    get("/weekly-closures"){secured(auth,call,Permission.VIEW_SETTLEMENTS){_->database(dataSource,call){it.closures()}}}
    post("/weekly-closures/{id}/reopen"){val request=call.receive<SettlementStatusCommand>();secured(auth,call,Permission.MANAGE_SETTLEMENTS){user->database(dataSource,call){it.reopenWeek(call.parameters["id"]!!,request.reason,user)}}}
    post("/milk-prices"){val request=call.receive<MilkPriceCommand>();secured(auth,call,Permission.MANAGE_MILK_PRICES){user->database(dataSource,call){it.createMilkPrice(request,user)}}}
    get("/milk-prices"){secured(auth,call,Permission.VIEW_MILK_PRICES){_->database(dataSource,call){it.milkPrices()}}}
    post("/settlements"){val request=call.receive<SettlementCommand>();secured(auth,call,Permission.MANAGE_SETTLEMENTS){user->database(dataSource,call){it.calculateSettlement(request,user)}}}
    get("/settlements"){secured(auth,call,Permission.VIEW_SETTLEMENTS,true){user->database(dataSource,call){it.settlements(user)}}}
    get("/settlements/{id}/envelope"){secured(auth,call,Permission.VIEW_SETTLEMENTS,true){user->database(dataSource,call){it.envelope(call.parameters["id"]!!,user)}}}
    post("/settlements/{id}/approve"){val request=call.receive<SettlementStatusCommand>();secured(auth,call,Permission.MANAGE_SETTLEMENTS){user->database(dataSource,call){it.changeSettlementStatus(call.parameters["id"]!!,"APPROVED",request.reason,user)}}}
    post("/settlements/{id}/cancel"){val request=call.receive<SettlementStatusCommand>();secured(auth,call,Permission.MANAGE_SETTLEMENTS){user->database(dataSource,call){it.changeSettlementStatus(call.parameters["id"]!!,"CANCELLED",request.reason,user)}}}
    post("/payments"){val request=call.receive<PaymentCommand>();secured(auth,call,Permission.MANAGE_PAYMENTS){user->database(dataSource,call){it.pay(request,user)}}}
    get("/payments"){secured(auth,call,Permission.VIEW_PAYMENTS,true){user->database(dataSource,call){it.payments(user,call.request.queryParameters["settlementId"])}}}
    post("/payments/{id}/cancel"){val request=call.receive<PaymentStatusCommand>();secured(auth,call,Permission.MANAGE_PAYMENTS){user->database(dataSource,call){it.cancelPayment(call.parameters["id"]!!,request.reason,user)}}}
    post("/production-batches"){val request=call.receive<ProductionBatchCommand>();secured(auth,call,Permission.MANAGE_PRODUCTION){user->database(dataSource,call){it.production(request,user)}}}
    get("/production-batches"){secured(auth,call,Permission.VIEW_PRODUCTION){_->database(dataSource,call){it.productionBatches()}}}
    get("/production-batches/{id}/yield"){secured(auth,call,Permission.VIEW_PRODUCTION){_->database(dataSource,call){it.productionYield(call.parameters["id"]!!)}}}
    post("/sales"){val request=call.receive<SaleCommand>();secured(auth,call,Permission.MANAGE_SALES){user->database(dataSource,call){it.sale(request,user)}}}
    get("/sales"){secured(auth,call,Permission.VIEW_SALES){_->database(dataSource,call){it.sales()}}}
    get("/inventory"){secured(auth,call,Permission.VIEW_PRODUCTION){_->database(dataSource,call){it.inventory()}}}
    get("/reports/financial"){secured(auth,call,Permission.VIEW_FINANCIAL_REPORTS){_->database(dataSource,call){it.financialReport()}}}
    get("/reports/production"){secured(auth,call,Permission.VIEW_FINANCIAL_REPORTS){_->database(dataSource,call){it.productionReport()}}}
}}

private suspend fun secured(auth:AuthService?,call:ApplicationCall,permission:Permission,self:Boolean=false,block:suspend(AuthenticatedUser)->Unit){val user=(auth?.let{withContext(Dispatchers.IO){it.me(call.request.headers[HttpHeaders.Authorization]?.removePrefix("Bearer ").orEmpty())}} as? AppResult.Success)?.value;if(user!=null&&(Authorization.allows(user,permission)||(self&&user.role==Role.PROVEEDOR)))block(user)else call.respond(HttpStatusCode.Forbidden,ApiEnvelope<Unit>(error=ApiErrorDto("FORBIDDEN","No tienes permiso para esta operación")))}
private suspend fun <T> database(dataSource:HikariDataSource?,call:ApplicationCall,block:(FinanceRepository)->T){if(dataSource==null){call.respond(HttpStatusCode.ServiceUnavailable,ApiEnvelope<Unit>(error=ApiErrorDto("UNAVAILABLE","Base de datos no configurada")));return};try{call.respond(ApiEnvelope(data=withContext(Dispatchers.IO){block(FinanceRepository(dataSource))}))}catch(error:IllegalArgumentException){call.respond(HttpStatusCode.BadRequest,ApiEnvelope<Unit>(error=ApiErrorDto("VALIDATION",error.message?:"Solicitud inválida")))}catch(error:IllegalStateException){call.respond(HttpStatusCode.Conflict,ApiEnvelope<Unit>(error=ApiErrorDto("CONFLICT",error.message?:"Operación no permitida")))}}

private class FinanceRepository(private val dataSource:HikariDataSource){
    fun closeWeek(request:WeeklyClosureCommand,user:AuthenticatedUser)=tx{connection->
        val start=LocalDate.parse(request.weekStart);val end=LocalDate.parse(request.weekEnd);BusinessCalendar.requireOperationalWeek(start,end)
        check(!exists(connection,"SELECT 1 FROM weekly_collection_closure WHERE week_start=? AND week_end=?",Date.valueOf(start),Date.valueOf(end))){"El período ya fue cerrado"}
        val providers=linkedMapOf<String,Pair<BigDecimal,BigDecimal>>()
        connection.prepareStatement("SELECT provider_id,SUM(liters) FROM milk_collection WHERE DATE(collected_at) BETWEEN ? AND ? AND status='SYNCED' GROUP BY provider_id").use{s->s.setDate(1,Date.valueOf(start));s.setDate(2,Date.valueOf(end));s.executeQuery().use{r->while(r.next())providers[r.getString(1)]=r.getBigDecimal(2) to BigDecimal.ZERO}}
        connection.prepareStatement("SELECT provider_id,SUM(liters) FROM direct_delivery WHERE DATE(delivered_at) BETWEEN ? AND ? AND status='CONFIRMED' GROUP BY provider_id").use{s->s.setDate(1,Date.valueOf(start));s.setDate(2,Date.valueOf(end));s.executeQuery().use{r->while(r.next()){val current=providers[r.getString(1)]?:BigDecimal.ZERO to BigDecimal.ZERO;providers[r.getString(1)]=current.first to r.getBigDecimal(2)}}}
        val id=UUID.randomUUID().toString();val total=providers.values.fold(BigDecimal.ZERO){sum,value->sum+value.first+value.second}
        connection.prepareStatement("INSERT INTO weekly_collection_closure(id,week_start,week_end,closed_by,total_liters,provider_count) VALUES(?,?,?,?,?,?)").use{s->s.setString(1,id);s.setDate(2,Date.valueOf(start));s.setDate(3,Date.valueOf(end));s.setString(4,user.userId);s.setBigDecimal(5,total);s.setInt(6,providers.size);s.executeUpdate()}
        connection.prepareStatement("INSERT INTO weekly_collection_closure_provider(closure_id,provider_id,field_liters,direct_liters,total_liters) VALUES(?,?,?,?,?)").use{s->providers.forEach{(provider,value)->s.setString(1,id);s.setString(2,provider);s.setBigDecimal(3,value.first);s.setBigDecimal(4,value.second);s.setBigDecimal(5,value.first+value.second);s.addBatch()};s.executeBatch()}
        audit(connection,user.userId,"WEEKLY_COLLECTION_CLOSED","WEEKLY_COLLECTION_CLOSURE",id);FinancialRecord(id,"","$start/$end",total.toPlainString(),"CLOSED")
    }
    fun closures()=records("SELECT id,'',CONCAT(week_start,'/',week_end),total_liters,status FROM weekly_collection_closure ORDER BY week_start DESC")
    fun reopenWeek(id:String,reason:String,user:AuthenticatedUser)=tx{connection->require(reason.isNotBlank()){ "El motivo es obligatorio" };val row=connection.prepareStatement("SELECT status,week_start,week_end,total_liters,provider_count FROM weekly_collection_closure WHERE id=? FOR UPDATE").use{s->s.setString(1,id);s.executeQuery().use{r->check(r.next()){ "Cierre inexistente" };arrayOf(r.getString(1),r.getDate(2),r.getDate(3),r.getBigDecimal(4),r.getInt(5))}};check(row[0]=="CLOSED"){"Solo se puede reabrir un cierre cerrado"};val snapshot="{\"weekStart\":\"${row[1]}\",\"weekEnd\":\"${row[2]}\",\"totalLiters\":\"${row[3]}\",\"providerCount\":${row[4]}}";connection.prepareStatement("INSERT INTO weekly_collection_closure_revision(id,closure_id,previous_status,new_status,reason,changed_by,snapshot) VALUES(?,?,?,?,?,?,?)").use{s->s.setString(1,UUID.randomUUID().toString());s.setString(2,id);s.setString(3,"CLOSED");s.setString(4,"REOPENED");s.setString(5,reason);s.setString(6,user.userId);s.setString(7,snapshot);s.executeUpdate()};connection.prepareStatement("UPDATE weekly_collection_closure SET status='REOPENED' WHERE id=?").use{s->s.setString(1,id);s.executeUpdate()};audit(connection,user.userId,"WEEKLY_COLLECTION_REOPENED","WEEKLY_COLLECTION_CLOSURE",id);FinancialRecord(id,"",reason,(row[3] as BigDecimal).toPlainString(),"REOPENED")}
    fun createMilkPrice(request:MilkPriceCommand,user:AuthenticatedUser)=tx{connection->val amount=request.amount.toBigDecimalOrNull()?:error("Monto inválido");require(amount>BigDecimal.ZERO);val start=Date.valueOf(request.effectiveFrom);val end=request.effectiveTo?.let(Date::valueOf);check(!exists(connection,"SELECT 1 FROM milk_price WHERE criterion=? AND status='ACTIVE' AND effective_from<=COALESCE(?,'9999-12-31') AND (effective_to IS NULL OR effective_to>=?)",request.criterion,end,start)){"Vigencia solapada"};val version=scalarLong(connection,"SELECT COALESCE(MAX(version),0)+1 FROM milk_price WHERE criterion=?",request.criterion);val id=UUID.randomUUID().toString();connection.prepareStatement("INSERT INTO milk_price(id,criterion,amount,currency,effective_from,effective_to,version,created_by,reason) VALUES(?,?,?,?,?,?,?,?,?)").use{s->s.setString(1,id);s.setString(2,request.criterion);s.setBigDecimal(3,amount);s.setString(4,request.currency);s.setDate(5,start);s.setDate(6,end);s.setLong(7,version);s.setString(8,user.userId);s.setString(9,request.reason);s.executeUpdate()};audit(connection,user.userId,"MILK_PRICE_CREATED","MILK_PRICE",id);FinancialRecord(id,request.criterion,"v$version",amount.toPlainString(),"ACTIVE")}
    fun milkPrices()=records("SELECT id,criterion,CONCAT('v',version),amount,status FROM milk_price ORDER BY effective_from DESC")
    fun calculateSettlement(request:SettlementCommand,user:AuthenticatedUser)=tx{connection->check(!exists(connection,"SELECT 1 FROM settlement WHERE provider_id=? AND weekly_closure_id=?",request.providerId,request.weeklyClosureId)){"Liquidación duplicada"};val liters=scalar(connection,"SELECT total_liters FROM weekly_collection_closure_provider WHERE closure_id=? AND provider_id=?",request.weeklyClosureId,request.providerId);val date=queryDate(connection,"SELECT week_end FROM weekly_collection_closure WHERE id=? AND status='CLOSED'",request.weeklyClosureId);val price=connection.prepareStatement("SELECT id,amount,currency,version FROM milk_price WHERE criterion='BASE' AND status='ACTIVE' AND effective_from<=? AND (effective_to IS NULL OR effective_to>=?) ORDER BY effective_from DESC LIMIT 1").use{s->s.setDate(1,date);s.setDate(2,date);s.executeQuery().use{r->check(r.next()){ "Precio de leche no encontrado" };arrayOf(r.getString(1),r.getBigDecimal(2),r.getString(3),r.getLong(4))}};val unitPrice=price[1] as BigDecimal;val gross=liters.multiply(unitPrice).setScale(4,RoundingMode.HALF_UP);val id=UUID.randomUUID().toString();connection.prepareStatement("INSERT INTO settlement(id,provider_id,weekly_closure_id,liters,base_price,currency,gross_amount,net_amount,calculated_by,price_id,price_version) VALUES(?,?,?,?,?,?,?,?,?,?,?)").use{s->s.setString(1,id);s.setString(2,request.providerId);s.setString(3,request.weeklyClosureId);s.setBigDecimal(4,liters);s.setBigDecimal(5,unitPrice);s.setString(6,price[2] as String);s.setBigDecimal(7,gross);s.setBigDecimal(8,gross);s.setString(9,user.userId);s.setString(10,price[0] as String);s.setLong(11,price[3] as Long);s.executeUpdate()};audit(connection,user.userId,"SETTLEMENT_CALCULATED","SETTLEMENT",id);FinancialRecord(id,request.providerId,request.weeklyClosureId,gross.toPlainString(),"CALCULATED")}
    fun settlements(user:AuthenticatedUser)=if(user.role==Role.PROVEEDOR)records("SELECT id,provider_id,weekly_closure_id,net_amount,status FROM settlement WHERE provider_id=? ORDER BY calculated_at DESC",listOf(requireNotNull(user.providerId)))else records("SELECT id,provider_id,weekly_closure_id,net_amount,status FROM settlement ORDER BY calculated_at DESC")
    fun changeSettlementStatus(id:String,status:String,reason:String,user:AuthenticatedUser)=tx{connection->require(reason.isNotBlank()){ "El motivo es obligatorio" };val current=queryString(connection,"SELECT status FROM settlement WHERE id=?",id);check(current in if(status=="APPROVED")setOf("DRAFT","CALCULATED")else setOf("DRAFT","CALCULATED","APPROVED")){"Cambio de estado no permitido"};connection.prepareStatement("UPDATE settlement SET status=? WHERE id=?").use{s->s.setString(1,status);s.setString(2,id);s.executeUpdate()};audit(connection,user.userId,"SETTLEMENT_$status","SETTLEMENT",id);FinancialRecord(id,"",reason,"0",status)}
    fun envelope(id:String,user:AuthenticatedUser):PaymentEnvelope=dataSource.connection.use{connection->connection.prepareStatement("SELECT s.id,s.provider_id,CONCAT(p.first_name,' ',p.last_name),w.week_start,w.week_end,s.liters,s.base_price,s.gross_amount,s.quality_adjustment,s.net_amount,COALESCE(SUM(CASE WHEN pay.status='CONFIRMED' THEN pay.amount ELSE 0 END),0),s.currency,s.status FROM settlement s JOIN provider p ON p.id=s.provider_id JOIN weekly_collection_closure w ON w.id=s.weekly_closure_id LEFT JOIN payment pay ON pay.settlement_id=s.id WHERE s.id=? GROUP BY s.id,s.provider_id,p.first_name,p.last_name,w.week_start,w.week_end,s.liters,s.base_price,s.gross_amount,s.quality_adjustment,s.net_amount,s.currency,s.status").use{s->s.setString(1,id);s.executeQuery().use{r->check(r.next()){ "Liquidación inexistente" };check(user.role!=Role.PROVEEDOR||user.providerId==r.getString(2)){"Liquidación no disponible"};val net=r.getBigDecimal(10);val paid=r.getBigDecimal(11);PaymentEnvelope(r.getString(1),r.getString(2),r.getString(3),r.getDate(4).toString(),r.getDate(5).toString(),r.getBigDecimal(6).toPlainString(),r.getBigDecimal(7).toPlainString(),r.getBigDecimal(8).toPlainString(),r.getBigDecimal(9).toPlainString(),net.toPlainString(),paid.toPlainString(),net.subtract(paid).toPlainString(),r.getString(12),r.getString(13))}}}
    fun pay(request:PaymentCommand,user:AuthenticatedUser)=tx{connection->val settlement=connection.prepareStatement("SELECT provider_id,net_amount,currency,status FROM settlement WHERE id=? FOR UPDATE").use{s->s.setString(1,request.settlementId);s.executeQuery().use{r->check(r.next()){ "Liquidación inexistente" };arrayOf(r.getString(1),r.getBigDecimal(2),r.getString(3),r.getString(4))}};check(settlement[3] in setOf("CALCULATED","APPROVED","PARTIALLY_PAID")){"La liquidación no admite pagos"};val amount=request.amount.toBigDecimalOrNull()?:error("Monto inválido");require(request.method.matches(Regex("[A-Z][A-Z0-9_]{1,39}"))){"Método de pago inválido"};check(request.currency==settlement[2]){"Moneda distinta a la liquidación"};val paid=scalar(connection,"SELECT COALESCE(SUM(amount),0) FROM payment WHERE settlement_id=? AND status='CONFIRMED'",request.settlementId);val balance=PaymentPolicy.apply(settlement[1] as BigDecimal,paid,amount);val id=UUID.randomUUID().toString();connection.prepareStatement("INSERT INTO payment(id,settlement_id,provider_id,amount,currency,paid_at,method,reference,notes,registered_by) VALUES(?,?,?,?,?,?,?,?,?,?)").use{s->s.setString(1,id);s.setString(2,request.settlementId);s.setString(3,settlement[0] as String);s.setBigDecimal(4,amount);s.setString(5,request.currency);s.setTimestamp(6,Timestamp.from(Instant.parse(request.paidAt)));s.setString(7,request.method);s.setString(8,request.reference);s.setString(9,request.notes);s.setString(10,user.userId);s.executeUpdate()};connection.prepareStatement("UPDATE settlement SET status=? WHERE id=?").use{s->s.setString(1,balance.settlementStatus);s.setString(2,request.settlementId);s.executeUpdate()};audit(connection,user.userId,"PAYMENT_REGISTERED","PAYMENT",id);FinancialRecord(id,settlement[0] as String,request.settlementId,balance.pending.toPlainString(),balance.settlementStatus)}
    fun cancelPayment(id:String,reason:String,user:AuthenticatedUser)=tx{connection->require(reason.isNotBlank()){ "El motivo es obligatorio" };val payment=connection.prepareStatement("SELECT settlement_id,provider_id,status FROM payment WHERE id=? FOR UPDATE").use{s->s.setString(1,id);s.executeQuery().use{r->check(r.next()){ "Pago inexistente" };arrayOf(r.getString(1),r.getString(2),r.getString(3))}};check(payment[2]=="CONFIRMED"){"El pago ya no está vigente"};connection.prepareStatement("UPDATE payment SET status='CANCELLED',cancelled_at=CURRENT_TIMESTAMP(6),cancelled_by=?,cancellation_reason=? WHERE id=?").use{s->s.setString(1,user.userId);s.setString(2,reason);s.setString(3,id);s.executeUpdate()};val net=scalar(connection,"SELECT net_amount FROM settlement WHERE id=?",payment[0]);val paid=scalar(connection,"SELECT COALESCE(SUM(amount),0) FROM payment WHERE settlement_id=? AND status='CONFIRMED'",payment[0]);val status=when{paid.signum()==0->"APPROVED";paid.compareTo(net)==0->"PAID";else->"PARTIALLY_PAID"};connection.prepareStatement("UPDATE settlement SET status=? WHERE id=?").use{s->s.setString(1,status);s.setString(2,payment[0] as String);s.executeUpdate()};audit(connection,user.userId,"PAYMENT_CANCELLED","PAYMENT",id);FinancialRecord(id,payment[1] as String,payment[0] as String,net.subtract(paid).toPlainString(),status)}
    fun payments(user:AuthenticatedUser,settlementId:String?):List<FinancialRecord>{val clauses=mutableListOf<String>();val args=mutableListOf<String>();if(user.role==Role.PROVEEDOR){clauses+="provider_id=?";args+=requireNotNull(user.providerId)};if(settlementId!=null){clauses+="settlement_id=?";args+=settlementId};return records("SELECT id,provider_id,CONCAT(method,' ',COALESCE(reference,'')),amount,status FROM payment ${if(clauses.isEmpty())""else"WHERE "+clauses.joinToString(" AND ")} ORDER BY paid_at DESC",args)}
    fun production(request:ProductionBatchCommand,user:AuthenticatedUser)=tx{connection->val input=request.inputQuantity.toBigDecimal();val output=request.outputQuantity.toBigDecimal();require(input>BigDecimal.ZERO&&output>BigDecimal.ZERO);check(exists(connection,"SELECT 1 FROM product WHERE id=? AND status='ACTIVE'",request.productId));val id=UUID.randomUUID().toString();connection.prepareStatement("INSERT INTO production_batch(id,batch_code,production_date,created_by,notes) VALUES(?,?,?,?,?)").use{s->s.setString(1,id);s.setString(2,request.batchCode);s.setDate(3,Date.valueOf(request.productionDate));s.setString(4,user.userId);s.setString(5,request.notes);s.executeUpdate()};connection.prepareStatement("INSERT INTO production_input(id,batch_id,input_type,quantity,unit) VALUES(?,?,?,?,?)").use{s->s.setString(1,UUID.randomUUID().toString());s.setString(2,id);s.setString(3,"MILK");s.setBigDecimal(4,input);s.setString(5,request.inputUnit);s.executeUpdate()};val outputId=UUID.randomUUID().toString();connection.prepareStatement("INSERT INTO production_output(id,batch_id,product_id,quantity,unit) VALUES(?,?,?,?,?)").use{s->s.setString(1,outputId);s.setString(2,id);s.setString(3,request.productId);s.setBigDecimal(4,output);s.setString(5,request.outputUnit);s.executeUpdate()};movement(connection,request.productId,"IN",output,"PRODUCTION_OUTPUT",outputId,user.userId);audit(connection,user.userId,"PRODUCTION_BATCH_CREATED","PRODUCTION_BATCH",id);FinancialRecord(id,request.productId,request.batchCode,output.toPlainString(),"RECORDED")}
    fun productionBatches()=records("SELECT id,'',batch_code,'0',status FROM production_batch ORDER BY production_date DESC")
    fun productionYield(id:String):FinancialRecord=dataSource.connection.use{connection->val input=scalar(connection,"SELECT COALESCE(SUM(quantity),0) FROM production_input WHERE batch_id=?",id);val output=scalar(connection,"SELECT COALESCE(SUM(quantity),0) FROM production_output WHERE batch_id=?",id);val ratio=if(input.signum()==0)BigDecimal.ZERO else output.divide(input,6,RoundingMode.HALF_UP);FinancialRecord(id,id,"YIELD",ratio.toPlainString(),"PENDING_VALIDATION")}
    fun sale(request:SaleCommand,user:AuthenticatedUser)=tx{connection->check(exists(connection,"SELECT 1 FROM customer WHERE id=? AND status='ACTIVE'",request.customerId));require(request.items.isNotEmpty());val date=Instant.parse(request.soldAt).atZone(BusinessCalendar.zone).toLocalDate();data class Item(val command:SaleItemCommand,val priceId:String,val price:BigDecimal,val subtotal:BigDecimal);val items=request.items.map{item->val quantity=item.quantity.toBigDecimal();require(quantity>BigDecimal.ZERO);check(exists(connection,"SELECT 1 FROM product WHERE id=? AND status='ACTIVE'",item.productId));check(stock(connection,item.productId)>=quantity){"Stock insuficiente"};val price=connection.prepareStatement("SELECT id,amount FROM product_price WHERE product_id=? AND customer_type=? AND status='ACTIVE' AND effective_from<=? AND (effective_to IS NULL OR effective_to>=?) ORDER BY effective_from DESC LIMIT 1").use{s->s.setString(1,item.productId);s.setString(2,item.customerType);s.setDate(3,Date.valueOf(date));s.setDate(4,Date.valueOf(date));s.executeQuery().use{r->check(r.next()){ "Precio vigente no encontrado" };r.getString(1) to r.getBigDecimal(2)}};Item(item,price.first,price.second,quantity.multiply(price.second).setScale(4,RoundingMode.HALF_UP))};val total=items.fold(BigDecimal.ZERO){sum,item->sum+item.subtotal};val id=UUID.randomUUID().toString();connection.prepareStatement("INSERT INTO sale(id,customer_id,sold_at,seller_user_id,currency,total) VALUES(?,?,?,?,?,?)").use{s->s.setString(1,id);s.setString(2,request.customerId);s.setTimestamp(3,Timestamp.from(Instant.parse(request.soldAt)));s.setString(4,user.userId);s.setString(5,request.currency);s.setBigDecimal(6,total);s.executeUpdate()};items.forEach{item->val itemId=UUID.randomUUID().toString();val quantity=item.command.quantity.toBigDecimal();connection.prepareStatement("INSERT INTO sale_item(id,sale_id,product_id,quantity,unit_price,subtotal,price_id) VALUES(?,?,?,?,?,?,?)").use{s->s.setString(1,itemId);s.setString(2,id);s.setString(3,item.command.productId);s.setBigDecimal(4,quantity);s.setBigDecimal(5,item.price);s.setBigDecimal(6,item.subtotal);s.setString(7,item.priceId);s.executeUpdate()};movement(connection,item.command.productId,"OUT",quantity,"SALE_ITEM",itemId,user.userId)};audit(connection,user.userId,"SALE_REGISTERED","SALE",id);FinancialRecord(id,request.customerId,"SALE",total.toPlainString(),"CONFIRMED")}
    fun sales()=records("SELECT id,customer_id,'SALE',total,status FROM sale ORDER BY sold_at DESC")
    fun inventory()=records("SELECT product_id,product_id,'STOCK',SUM(CASE WHEN movement_type='IN' THEN quantity ELSE -quantity END),'AVAILABLE' FROM inventory_movement GROUP BY product_id ORDER BY product_id")
    fun financialReport()=records("SELECT 'TOTAL_SETTLED','','TOTAL_LIQUIDADO',COALESCE(SUM(net_amount),0),'AVAILABLE' FROM settlement WHERE status<>'CANCELLED' UNION ALL SELECT 'TOTAL_PAID','','TOTAL_PAGADO',COALESCE(SUM(amount),0),'AVAILABLE' FROM payment WHERE status='CONFIRMED' UNION ALL SELECT 'PENDING_BALANCE','','SALDO_PENDIENTE',(SELECT COALESCE(SUM(net_amount),0) FROM settlement WHERE status<>'CANCELLED')-(SELECT COALESCE(SUM(amount),0) FROM payment WHERE status='CONFIRMED'),'AVAILABLE'")
    fun productionReport()=records("SELECT batch.id,output.product_id,batch.batch_code,output.quantity,batch.status FROM production_batch batch JOIN production_output output ON output.batch_id=batch.id ORDER BY batch.production_date DESC")
    private fun stock(connection:Connection,productId:String)=scalar(connection,"SELECT COALESCE(SUM(CASE WHEN movement_type='IN' THEN quantity ELSE -quantity END),0) FROM inventory_movement WHERE product_id=?",productId)
    private fun movement(connection:Connection,productId:String,type:String,quantity:BigDecimal,sourceType:String,sourceId:String,userId:String){connection.prepareStatement("INSERT INTO inventory_movement(id,product_id,movement_type,quantity,occurred_at,source_type,source_id,created_by) VALUES(?,?,?,?,CURRENT_TIMESTAMP(6),?,?,?)").use{s->s.setString(1,UUID.randomUUID().toString());s.setString(2,productId);s.setString(3,type);s.setBigDecimal(4,quantity);s.setString(5,sourceType);s.setString(6,sourceId);s.setString(7,userId);s.executeUpdate()}}
    private fun records(sql:String,args:List<String> = emptyList()):List<FinancialRecord> = dataSource.connection.use{connection->connection.prepareStatement(sql).use{s->args.forEachIndexed{index,value->s.setString(index+1,value)};s.executeQuery().use{r->buildList{while(r.next())add(FinancialRecord(r.getString(1),r.getString(2),r.getString(3),r.getBigDecimal(4).toPlainString(),r.getString(5)))}}}}
    private fun scalar(connection:Connection,sql:String,vararg args:Any?):BigDecimal=connection.prepareStatement(sql).use{s->bind(s,args);s.executeQuery().use{r->check(r.next());r.getBigDecimal(1)}}
    private fun scalarLong(connection:Connection,sql:String,vararg args:Any?):Long=connection.prepareStatement(sql).use{s->bind(s,args);s.executeQuery().use{r->r.next();r.getLong(1)}}
    private fun queryDate(connection:Connection,sql:String,vararg args:Any?):Date=connection.prepareStatement(sql).use{s->bind(s,args);s.executeQuery().use{r->check(r.next());r.getDate(1)}}
    private fun queryString(connection:Connection,sql:String,vararg args:Any?):String=connection.prepareStatement(sql).use{s->bind(s,args);s.executeQuery().use{r->check(r.next()){ "Registro inexistente" };r.getString(1)}}
    private fun exists(connection:Connection,sql:String,vararg args:Any?):Boolean=connection.prepareStatement(sql).use{s->bind(s,args);s.executeQuery().use{it.next()}}
    private fun bind(statement:PreparedStatement,args:Array<out Any?>){args.forEachIndexed{index,value->statement.setObject(index+1,value)}}
    private fun <T> tx(block:(Connection)->T):T=dataSource.connection.use{connection->connection.autoCommit=false;try{val value=block(connection);connection.commit();value}catch(error:Exception){connection.rollback();throw error}}
    private fun audit(connection:Connection,actor:String,action:String,type:String,id:String){connection.prepareStatement("INSERT INTO audit_event(id,actor_user_id,action,entity_type,entity_id) VALUES(?,?,?,?,?)").use{s->s.setString(1,UUID.randomUUID().toString());s.setString(2,actor);s.setString(3,action);s.setString(4,type);s.setString(5,id);s.executeUpdate()}}
}
