package pe.gob.huata.ecolactea.server.seed

import pe.gob.huata.ecolactea.server.*
import pe.gob.huata.ecolactea.server.auth.PasswordHasher
import java.math.BigDecimal
import java.nio.charset.StandardCharsets
import java.sql.Connection
import java.time.*
import java.util.UUID

private fun id(s:String)=UUID.nameUUIDFromBytes(("ecolactea-dev:"+s).toByteArray(StandardCharsets.UTF_8)).toString()
private fun Connection.x(sql:String,vararg v:Any?){prepareStatement(sql).use{s->v.forEachIndexed{i,a->s.setObject(i+1,a)};s.executeUpdate()}}
private fun Connection.b(sql:String,rs:List<List<Any?>>){prepareStatement(sql).use{s->rs.forEach{r->r.forEachIndexed{i,a->s.setObject(i+1,a)};s.addBatch()};s.executeBatch()}}
private fun d(s:String)=BigDecimal(s)
private fun t(d:LocalDate,h:Int=12)=LocalDateTime.of(d,LocalTime.of(h,0))

fun main(){
 val e=ExternalConfig.load()
 val password=e["DEV_SEED_PASSWORD"]?.takeIf{it.isNotBlank()}?:error("DEV_SEED_PASSWORD is required")
 require(e["DB_URL"].orEmpty().contains("ecolactea_dev",true)){"Refusing DEV seed: DB_URL must target ecolactea_dev"}
 val ds=DatabaseFactory.connectAndMigrate(ServerConfig.fromEnvironment(e).database?:error("DB_URL required"))
 try{ds.connection.use{seed(it,password)}}finally{ds.close()}
 println("DEV seed completed; secrets were not printed.")
}

private fun seed(c:Connection,password:String){
 c.prepareStatement("SELECT GET_LOCK('ecolactea_dev_seed',30)").use{it.executeQuery().use{r->r.next()}}
 try{
  c.prepareStatement("SELECT 1 FROM app_user WHERE username='admin.dev'").use{s->s.executeQuery().use{if(it.next()){println("DEV seed already present; no duplicate rows inserted.");return}}}
  c.autoCommit=false
  val admin=id("admin"); val plant=(1..4).map{id("plant-"+it)}; val acop=(1..4).map{id("acop-"+it)}; val prov=(1..36).map{id("provider-"+it)}
  val h=PasswordHasher().hash(password)
  c.b("INSERT INTO app_user(id,username,password_hash,role_code,active,provider_id) VALUES(?,?,?,?,?,?)",listOf(listOf(admin,"admin.dev",h,"ADMINISTRADOR_GENERAL",true,null))+plant.mapIndexed{i,v->listOf(v,String.format("planta%02d.dev",i+1),h,"PERSONAL_PLANTA",i<3,null)}+acop.mapIndexed{i,v->listOf(v,String.format("acopiador%02d.dev",i+1),h,"ACOPIADOR",true,null)})
  c.b("INSERT INTO provider(id,code,dni,first_name,last_name,phone,farm_name,status) VALUES(?,?,?,?,?,?,?,?)",prov.mapIndexed{i,v->listOf(v,String.format("DEV-P%02d",i+1),String.format("990%08d",i+1),"Nombre "+(i+1),"Proveedor DEV",String.format("900%07d",i+1),"Fundo DEV "+(i+1),if(i>31)"INACTIVE" else "ACTIVE")})
  c.b("INSERT INTO app_user(id,username,password_hash,role_code,active,provider_id) VALUES(?,?,?,?,?,?)",(1..28).map{i->listOf(id("portal-"+i),String.format("proveedor%02d.dev",i),h,"PROVEEDOR",i<27,prov[i-1])})
  c.b("UPDATE provider SET portal_user_id=? WHERE id=?",(1..28).map{i->listOf(id("portal-"+i),prov[i-1])})
  val zones=(1..5).map{id("zone-"+it)};val routes=(1..10).map{id("route-"+it)};val units=(1..4).map{id("unit-"+it)}
  c.b("INSERT INTO zone(id,code,name,description,status) VALUES(?,?,?,?,?)",zones.mapIndexed{i,v->listOf(v,String.format("DEV-Z%02d",i+1),"Zona DEV "+(i+1),"Datos ficticios","ACTIVE")})
  c.b("INSERT INTO route(id,code,name,zone_id,description,status,valid_from) VALUES(?,?,?,?,?,?,?)",routes.mapIndexed{i,v->listOf(v,String.format("DEV-R%02d",i+1),"Ruta DEV "+(i+1),zones[i%5],"Datos ficticios","ACTIVE",LocalDate.now().minusMonths(4))})
  c.b("INSERT INTO collection_unit(id,code,plate_or_identifier,description,status) VALUES(?,?,?,?,?)",units.mapIndexed{i,v->listOf(v,String.format("DEV-U%02d",i+1),"DEV-VEH-"+(i+1),"Unidad DEV","ACTIVE")})
  c.b("INSERT INTO provider_route_assignment(id,provider_id,route_id,valid_from,valid_to,status,created_by,reason) VALUES(?,?,?,?,?,?,?,?)",prov.flatMapIndexed{i,p->listOf(listOf(id("old-assignment-"+i),p,routes[(i+1)%10],LocalDate.now().minusWeeks(12),LocalDate.now().minusWeeks(5),"HISTORICAL",admin,"Cambio DEV"),listOf(id("current-assignment-"+i),p,routes[i%10],LocalDate.now().minusWeeks(5).plusDays(1),null,"ACTIVE",admin,"Asignación DEV"))})
  val weeks=(2..9).map{LocalDate.now().minusWeeks(it.toLong()).with(DayOfWeek.MONDAY)}.sorted();val wd=mutableListOf<List<Any?>>();val mc=mutableListOf<List<Any?>>()
  weeks.forEachIndexed{wi,m->routes.forEachIndexed{ri,r->val date=m.plusDays((ri%5).toLong());val w=id("wd-"+wi+"-"+ri);wd+=listOf(w,date,r,units[ri%4]);c.x("INSERT INTO collection_workday(id,code,route_id,unit_id,work_date,planned_start_time,planned_end_time,status,created_by) VALUES(?,?,?,?,?,?,?,?,?)",w,"DEV-WD-"+wi+"-"+ri,r,units[ri%4],date,LocalTime.of(6,0),LocalTime.of(14,0),when{wi<5->"COMPLETED";wi==5->"CANCELLED";else->"SCHEDULED"},acop[ri%4]);c.b("INSERT INTO collection_workday_staff(workday_id,user_id,responsibility) VALUES(?,?,?)",listOf(listOf(w,acop[ri%4],"ACOPIO"),listOf(w,plant[ri%4],"RECEPCION")));(0 until 11).forEach{k->val pi=(ri*3+k)%36;mc+=listOf(id("collection-"+wi+"-"+ri+"-"+k),prov[pi],if(date.isBefore(LocalDate.now().minusWeeks(5)))routes[(pi+1)%10] else r,w,acop[ri%4],t(date,7+k%3),d(String.format("%d.%03d",18+k%8,(wi+k)%1000)),"DEV_ROUTE",id("collection-op-"+wi+"-"+ri+"-"+k),"SYNCED")}}}
  c.b("INSERT INTO milk_collection(id,provider_id,route_id,workday_id,collector_user_id,collected_at,liters,origin,client_operation_id,status) VALUES(?,?,?,?,?,?,?,?,?,?)",mc)
  val dd=(0 until 80).map{i->listOf(id("delivery-"+i),prov[i%36],t(LocalDate.now().minusDays((i*3L)%70),13),d(String.format("%d.500",30+i%18)),"DEV_DIRECT",plant[i%4],id("delivery-op-"+i),"CONFIRMED")}
  c.b("INSERT INTO direct_delivery(id,provider_id,delivered_at,liters,origin,responsible_user_id,client_operation_id,status) VALUES(?,?,?,?,?,?,?,?)",dd)
  wd.forEachIndexed{i,w->val total=mc.filter{it[3]==w[0]}.sumOf{(it[6] as BigDecimal).toDouble()};val received=total+if(i%7==0)2.5 else 0.0;val r=id("reception-"+i);c.x("INSERT INTO plant_reception(id,workday_id,route_id,collection_unit_id,received_at,liters_received,measurement_source,responsible_user_id,client_operation_id,status) VALUES(?,?,?,?,?,?,?,?,?,?)",r,w[0],w[2],w[3],t(w[1] as LocalDate,15),d("%.3f".format(java.util.Locale.US,received)),"DEV_SCALE",plant[i%4],id("reception-op-"+i),"CONFIRMED");val q=id("recon-"+i);val diff=received-total;c.x("INSERT INTO collection_reconciliation(id,workday_id,route_id,total_field,total_direct,total_expected,total_received,difference,difference_percentage,status,created_by) VALUES(?,?,?,?,?,?,?,?,?,?,?)",q,w[0],w[2],d("%.3f".format(java.util.Locale.US,total)),d("0"),d("%.3f".format(java.util.Locale.US,total)),d("%.3f".format(java.util.Locale.US,received)),d("%.3f".format(java.util.Locale.US,diff)),d("%.4f".format(java.util.Locale.US,diff/total*100)),if(diff==0.0)"MATCHED" else "DISCREPANCY",admin);if(diff!=0.0)c.x("INSERT INTO discrepancy_resolution(id,reconciliation_id,reason,observations,authorized_correction,resolved_by,status) VALUES(?,?,?,?,?,?,?)",id("resolution-"+i),q,"Diferencia DEV","Revisión DEV",d("2.500"),admin,"RESOLVED")}
  val keys=listOf("grasa","proteina","densidad","temperatura","acidez","ph","solidos_totales","solidos_no_grasos","lactosa","agua_anadida","punto_crioscopico","conductividad","antibioticos");val pids=keys.map{id("parameter-"+it)}
  c.b("INSERT INTO quality_parameter(id,\u0060key\u0060,name,unit,value_type,status,metadata) VALUES(?,?,?,?,?,?,?)",keys.mapIndexed{i,k->listOf(pids[i],"DEV_"+k,k.replace('_',' '),"DEV_UNIT","DECIMAL","ACTIVE",null)})
  val qa=mc.take(400).mapIndexed{i,row->val a=id("analysis-"+i);c.x("INSERT INTO quality_analysis(id,provider_id,source_type,source_id,sample_reference,analyzed_at,analyst_user_id,status,observations) VALUES(?,?,?,?,?,?,?,?,?)",a,row[1],"MILK_COLLECTION",row[0],"DEV-SAMPLE-"+i,row[5],plant[i%4],"RECORDED","Datos DEV; validación pendiente");a}
  c.b("INSERT INTO quality_test_result(id,analysis_id,parameter_id,decimal_value,text_value,unit,status) VALUES(?,?,?,?,?,?,?)",qa.flatMapIndexed{i,a->(0..2).map{j->listOf(id("result-"+i+"-"+j),a,pids[j],d((3+j).toString()+".5"),null,"DEV_UNIT","RECORDED")}})
  c.b("INSERT INTO quality_classification(id,analysis_id,classification,rule_version,status,classified_by,observations) VALUES(?,?,?,?,?,?,?)",qa.mapIndexed{i,a->listOf(id("classification-"+i),a,when{ i%9==0->"OBSERVED";i%5==0->"PENDING_VALIDATION";else->"APPROVED"},"DEV-PENDING-VALIDATION","RECORDED",plant[i%4],"DEV")})
  val inc=(0 until 45).map{i->listOf(id("incident-"+i),prov[i%36],qa[i],id("classification-"+i),"CALIDAD","Incidencia DEV "+i,if(i%4==0)"HIGH" else "MEDIUM",when{i%3==0->"CLOSED";i%3==1->"IN_PROGRESS";else->"OPEN"},t(LocalDate.now().minusDays(i.toLong())),plant[i%4],if(i%3==0)t(LocalDate.now().minusDays(i.toLong()-1))else null)}
  c.b("INSERT INTO quality_incident(id,provider_id,analysis_id,classification_id,category,description,severity,status,occurred_at,created_by,closed_at) VALUES(?,?,?,?,?,?,?,?,?,?,?)",inc)
  c.b("INSERT INTO quality_measure(id,incident_id,measure_type,description,starts_at,ends_at,status,responsible_user_id,approved_by,observations) VALUES(?,?,?,?,?,?,?,?,?,?)",(0 until 15).map{i->listOf(id("measure-"+i),inc[i][0],"VISITA","Medida DEV",t(LocalDate.now().minusDays(i.toLong())),null,"OPEN",plant[i%4],null,"DEV")})
  c.b("INSERT INTO technical_follow_up(id,provider_id,incident_id,follow_up_type,scheduled_at,performed_at,responsible_user_id,result,notes,status) VALUES(?,?,?,?,?,?,?,?,?,?)",(0 until 20).map{i->listOf(id("followup-"+i),prov[i%36],inc[i][0],"SEGUIMIENTO",t(LocalDate.now().minusDays(i.toLong())),null,plant[i%4],null,"DEV","SCHEDULED")})
  val ev=(0 until 20).map{i->listOf(id("event-"+i),if(i%2==0)"TRAINING" else "MEETING","Evento DEV "+i,"Comunicación DEV",t(LocalDate.now().minusDays((i*2).toLong())),t(LocalDate.now().minusDays((i*2).toLong()),14),"Planta DEV","PROVIDERS",when{i<5->"FINISHED";i<10->"PUBLISHED";i==19->"CANCELLED";else->"DRAFT"},null,admin)}
  c.b("INSERT INTO communication_event(id,event_type,title,description,starts_at,ends_at,location,audience,status,published_at,created_by) VALUES(?,?,?,?,?,?,?,?,?,?,?)",ev)
  c.b("INSERT INTO event_attendance(event_id,provider_id,status,marked_by,marking_method) VALUES(?,?,?,?,?)",ev.take(10).flatMapIndexed{i,e->(0 until 12+i).map{k->listOf(e[0],prov[(i+k)%36],if(k%5==0)"ABSENT" else "ATTENDED",admin,"MANUAL")}})
  c.b("INSERT INTO provider_notification(id,provider_id,notification_type,title,body,source_type,source_id,status,published_at,created_by) VALUES(?,?,?,?,?,?,?,?,?,?)",(0 until 36).map{i->listOf(id("notification-"+i),prov[i],"DEV_NOTICE","Aviso DEV "+i,"Notificación DEV","COMMUNICATION_EVENT",ev[i%20][0],"PUBLISHED",t(LocalDate.now().minusDays(i.toLong())),admin)})
  val prices=(0 until 4).map{i->listOf(id("milk-price-"+i),"BASE_DEV",d(String.format("%.2f",1.65+i*.05)),"PEN",weeks[i],if(i<3)weeks[i+1].minusDays(1)else null,"ACTIVE",i+1L,admin,"Precio DEV")}
  c.b("INSERT INTO milk_price(id,criterion,amount,currency,effective_from,effective_to,status,version,created_by,reason) VALUES(?,?,?,?,?,?,?,?,?,?)",prices)
  val closures=weeks.mapIndexed{i,start->val cl=id("closure-"+i);val rows=prov.map{p->val l=mc.filter{it[1]==p&&(it[5] as LocalDateTime).toLocalDate() in start..start.plusDays(6)}.sumOf{(it[6] as BigDecimal).toDouble()};listOf(cl,p,d("%.3f".format(java.util.Locale.US,l)),d("0"),d("%.3f".format(java.util.Locale.US,l)))};val total=rows.sumOf{(it[2] as BigDecimal).toDouble()};c.x("INSERT INTO weekly_collection_closure(id,week_start,week_end,status,closed_by,total_liters,provider_count,metadata) VALUES(?,?,?,?,?,?,?,?)",cl,start,start.plusDays(6),"CLOSED",admin,d("%.3f".format(java.util.Locale.US,total)),36,null);c.b("INSERT INTO weekly_collection_closure_provider(closure_id,provider_id,field_liters,direct_liters,total_liters) VALUES(?,?,?,?,?)",rows);cl}
  val st=closures.flatMapIndexed{wi,cl->prov.mapIndexed{pi,p->val l=d((18+pi%8).toString());val pr=prices[wi%4];val amount=l.multiply(pr[2] as BigDecimal).setScale(4);listOf(id("settlement-"+wi+"-"+pi),p,cl,l,pr[2],"PEN",amount,d("0"),d("0"),amount,when{pi%17==0->"PAID";pi%11==0->"PARTIALLY_PAID";pi%7==0->"APPROVED";else->"CALCULATED"},admin,pr[0],pr[7])}}
  c.b("INSERT INTO settlement(id,provider_id,weekly_closure_id,liters,base_price,currency,gross_amount,quality_adjustment,other_approved_adjustments,net_amount,status,calculated_by,price_id,price_version) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?)",st)
  val products=(1..8).map{id("product-"+it)};val customers=(1..20).map{id("customer-"+it)}
  c.b("INSERT INTO product(id,code,name,category,unit,status) VALUES(?,?,?,?,?,?)",products.mapIndexed{i,p->listOf(p,String.format("DEV-PR-%02d",i+1),listOf("Yogur DEV","Queso DEV","Leche DEV","Manjar DEV")[i%4],"LACTEOS",if(i%2==0)"UNIDAD" else "KG","ACTIVE")})
  c.b("INSERT INTO customer(id,code,name,document,customer_type,phone,status) VALUES(?,?,?,?,?,?,?)",customers.mapIndexed{i,x->listOf(x,String.format("DEV-C%02d",i+1),"Cliente DEV "+(i+1),"RUC-DEV-"+i,if(i%2==0)"MINORISTA" else "MAYORISTA","910"+i,"ACTIVE")})
  val pp=products.flatMapIndexed{i,p->listOf(listOf(id("price-old-"+i),p,"MAYORISTA",d((4+i).toString()+".50"),"PEN",weeks.first(),weeks[4].minusDays(1),"ACTIVE",admin,"Precio DEV"),listOf(id("price-current-"+i),p,"MAYORISTA",d((5+i).toString()+".00"),"PEN",weeks[4],null,"ACTIVE",admin,"Precio DEV"))}
  c.b("INSERT INTO product_price(id,product_id,customer_type,amount,currency,effective_from,effective_to,status,created_by,reason) VALUES(?,?,?,?,?,?,?,?,?,?)",pp)
  (0 until 30).forEach{i->val b=id("batch-"+i);val out=id("output-"+i);val date=LocalDate.now().minusDays((i*2L)%60);c.x("INSERT INTO production_batch(id,batch_code,production_date,status,created_by,notes) VALUES(?,?,?,?,?,?)",b,String.format("DEV-BATCH-%03d",i+1),date,"RECORDED",plant[i%4],"DEV");c.x("INSERT INTO production_input(id,batch_id,input_type,quantity,unit) VALUES(?,?,?,?,?)",id("input-"+i),b,"MILK",d((300+i*4).toString()),"LITERS");c.x("INSERT INTO production_output(id,batch_id,product_id,quantity,unit) VALUES(?,?,?,?,?)",out,b,products[i%8],d((80+i).toString()),"UNIDAD");c.x("INSERT INTO inventory_movement(id,product_id,movement_type,quantity,occurred_at,source_type,source_id,created_by) VALUES(?,?,?,?,?,?,?,?)",id("inventory-in-"+i),products[i%8],"IN",d((80+i).toString()),t(date),"PRODUCTION_OUTPUT",out,plant[i%4])}
  (0 until 60).forEach{i->val sale=id("sale-"+i);val item=id("sale-item-"+i);val price=pp[(i%8)*2+1];val q=d((1+i%3).toString());val sub=q.multiply(price[3] as BigDecimal).setScale(4);c.x("INSERT INTO sale(id,customer_id,sold_at,seller_user_id,status,currency,total) VALUES(?,?,?,?,?,?,?)",sale,customers[i%20],t(LocalDate.now().minusDays((i*2L)%60),17),plant[i%4],"CONFIRMED","PEN",sub);c.x("INSERT INTO sale_item(id,sale_id,product_id,quantity,unit_price,subtotal,price_id) VALUES(?,?,?,?,?,?,?)",item,sale,price[1],q,price[3],sub,price[0]);c.x("INSERT INTO inventory_movement(id,product_id,movement_type,quantity,occurred_at,source_type,source_id,created_by) VALUES(?,?,?,?,?,?,?,?)",id("inventory-out-"+i),price[1],"OUT",q,t(LocalDate.now().minusDays((i*2L)%60),17),"SALE_ITEM",item,plant[i%4])}
  c.commit();println("DEV dataset inserted: providers="+prov.size+" collections="+mc.size+" deliveries="+dd.size+" analyses="+qa.size+" incidents="+inc.size+" events="+ev.size+" closures="+closures.size+" settlements="+st.size+" products="+products.size+" customers="+customers.size+" production=30 sales=60")
 }catch(x:Throwable){c.rollback();throw x}finally{c.prepareStatement("SELECT RELEASE_LOCK('ecolactea_dev_seed')").use{it.executeQuery().use{r->r.next()}}}
}
