package pe.gob.huata.ecolactea.server.operations

import com.zaxxer.hikari.HikariDataSource
import io.ktor.http.HttpHeaders
import io.ktor.http.HttpStatusCode
import io.ktor.server.application.ApplicationCall
import io.ktor.server.application.call
import io.ktor.server.request.receive
import io.ktor.server.response.respond
import io.ktor.server.routing.*
import kotlinx.coroutines.Dispatchers
import kotlinx.coroutines.withContext
import kotlinx.serialization.Serializable
import pe.gob.huata.ecolactea.core.application.AppError
import pe.gob.huata.ecolactea.core.application.AppResult
import pe.gob.huata.ecolactea.core.model.AuthenticatedUser
import pe.gob.huata.ecolactea.core.model.Permission
import pe.gob.huata.ecolactea.core.network.ApiEnvelope
import pe.gob.huata.ecolactea.server.auth.AuthService
import java.math.BigDecimal
import java.sql.Connection
import java.sql.Date
import java.time.LocalDate
import java.util.UUID
import javax.sql.DataSource

@Serializable data class ProviderRequest(val dni: String, val firstName: String, val lastName: String, val phone: String, val farmName: String? = null)
@Serializable data class ProviderDto(val id: String, val code: String, val dni: String, val firstName: String, val lastName: String, val phone: String, val farmName: String?, val status: String)
@Serializable data class ZoneRequest(val code: String, val name: String, val description: String? = null)
@Serializable data class RouteRequest(val code: String, val name: String, val zoneId: String, val description: String? = null, val validFrom: String)
@Serializable data class AssignmentRequest(val routeId: String, val validFrom: String, val reason: String? = null)
@Serializable data class ProductRequest(val code: String, val name: String, val category: String, val unit: String)
@Serializable data class CustomerRequest(val code: String, val name: String, val document: String? = null, val customerType: String, val phone: String? = null)
@Serializable data class PriceRequest(val productId: String, val customerType: String, val amount: String, val currency: String, val effectiveFrom: String, val effectiveTo: String? = null, val reason: String)
@Serializable data class ParameterRequest(val key: String, val value: String, val valueType: String, val unit: String? = null, val effectiveFrom: String, val reason: String? = null)
@Serializable data class WorkdayRequest(val code: String, val routeId: String, val unitId: String, val workDate: String, val plannedStartTime: String, val plannedEndTime: String? = null)
@Serializable data class CollectionUnitRequest(val code: String, val plateOrIdentifier: String? = null, val description: String)
@Serializable data class WorkdayStaffRequest(val userId: String, val responsibility: String)
@Serializable data class SimpleRow(val id: String, val code: String, val name: String, val status: String)
@Serializable data class AuditDto(val id: String, val actorUserId: String, val action: String, val entityType: String, val entityId: String, val occurredAt: String, val reason: String? = null, val beforeData: String? = null, val afterData: String? = null)
@Serializable data class HistoryDto(val provider: ProviderDto, val assignments: List<SimpleRow>, val collections: List<SimpleRow> = emptyList(), val directDeliveries: List<SimpleRow> = emptyList(), val quality: List<SimpleRow> = emptyList(), val incidents: List<SimpleRow> = emptyList(), val weeklySummaries: List<SimpleRow> = emptyList(), val settlements: List<SimpleRow> = emptyList(), val payments: List<SimpleRow> = emptyList(), val unavailableSources: List<String> = emptyList())
@Serializable data class OperationalReportDto(val dateFrom: String? = null, val dateTo: String? = null, val providers: List<ProviderDto>, val zones: List<SimpleRow> = emptyList(), val routes: List<SimpleRow> = emptyList(), val workdays: List<SimpleRow> = emptyList(), val collections: List<SimpleRow> = emptyList(), val directDeliveries: List<SimpleRow> = emptyList(), val receptions: List<SimpleRow> = emptyList(), val reconciliations: List<SimpleRow> = emptyList(), val quality: List<SimpleRow> = emptyList(), val classifications: List<SimpleRow> = emptyList(), val incidents: List<SimpleRow> = emptyList(), val sourcesUnavailable: List<String> = emptyList())

fun Route.operationsRoutes(dataSource: HikariDataSource?, auth: AuthService?) {
    route("/api/v1") {
        get("/providers") { withUser(auth, call, Permission.VIEW_PROVIDERS) { db(dataSource, call) { it.providers() } } }
        post("/providers") { val request = call.receive<ProviderRequest>(); withUser(auth, call, Permission.MANAGE_PROVIDERS) { user -> db(dataSource, call) { it.createProvider(request, user.userId) } } }
        get("/providers/{id}") { withUser(auth, call, Permission.VIEW_PROVIDERS) { db(dataSource, call) { it.provider(requireId(call)) } } }
        put("/providers/{id}") { val request = call.receive<ProviderRequest>(); withUser(auth, call, Permission.MANAGE_PROVIDERS) { user -> db(dataSource, call) { it.updateProvider(requireId(call), request, user.userId) } } }
        post("/providers/{id}/activate") { withUser(auth, call, Permission.MANAGE_PROVIDERS) { user -> db(dataSource, call) { it.changeStatus("provider", requireId(call), "ACTIVE", user.userId, "PROVIDER") } } }
        post("/providers/{id}/deactivate") { withUser(auth, call, Permission.MANAGE_PROVIDERS) { user -> db(dataSource, call) { it.changeStatus("provider", requireId(call), "INACTIVE", user.userId, "PROVIDER") } } }
        post("/providers/{id}/assignments") { val request = call.receive<AssignmentRequest>(); withUser(auth, call, Permission.MANAGE_ROUTES) { user -> db(dataSource, call) { it.assign(requireId(call), request, user.userId) } } }
        get("/providers/{id}/history") { withUser(auth, call, Permission.MANAGE_PROVIDERS, allowSelf = true) { user ->
            val requested = requireId(call)
            if (user.role.name == "PROVEEDOR" && user.providerId != requested) forbidden(call) else db(dataSource, call) { it.history(requested) }
        } }

        get("/zones") { withUser(auth, call, Permission.VIEW_ROUTES) { db(dataSource, call) { it.simple("zone") } } }
        post("/zones") { val request = call.receive<ZoneRequest>(); withUser(auth, call, Permission.MANAGE_ROUTES) { user -> db(dataSource, call) { it.createZone(request, user.userId) } } }
        put("/zones/{id}") { val request = call.receive<ZoneRequest>(); withUser(auth, call, Permission.MANAGE_ROUTES) { user -> db(dataSource, call) { it.updateZone(requireId(call), request, user.userId) } } }
        post("/zones/{id}/activate") { withUser(auth, call, Permission.MANAGE_ROUTES) { user -> db(dataSource, call) { it.changeStatus("zone", requireId(call), "ACTIVE", user.userId, "ZONE") } } }
        post("/zones/{id}/deactivate") { withUser(auth, call, Permission.MANAGE_ROUTES) { user -> db(dataSource, call) { it.changeStatus("zone", requireId(call), "INACTIVE", user.userId, "ZONE") } } }
        get("/routes") { withUser(auth, call, Permission.VIEW_ROUTES) { db(dataSource, call) { it.simpleRoutes(call.request.queryParameters["zoneId"]) } } }
        post("/routes") { val request = call.receive<RouteRequest>(); withUser(auth, call, Permission.MANAGE_ROUTES) { user -> db(dataSource, call) { it.createRoute(request, user.userId) } } }
        put("/routes/{id}") { val request = call.receive<RouteRequest>(); withUser(auth, call, Permission.MANAGE_ROUTES) { user -> db(dataSource, call) { it.updateRoute(requireId(call), request, user.userId) } } }
        post("/routes/{id}/activate") { withUser(auth, call, Permission.MANAGE_ROUTES) { user -> db(dataSource, call) { it.changeStatus("route", requireId(call), "ACTIVE", user.userId, "ROUTE") } } }
        post("/routes/{id}/deactivate") { withUser(auth, call, Permission.MANAGE_ROUTES) { user -> db(dataSource, call) { it.changeStatus("route", requireId(call), "INACTIVE", user.userId, "ROUTE") } } }
        get("/collection-units") { withUser(auth, call, Permission.VIEW_WORKDAYS) { db(dataSource, call) { it.simple("collection_unit") } } }
        post("/collection-units") { val request = call.receive<CollectionUnitRequest>(); withUser(auth, call, Permission.MANAGE_WORKDAYS) { user -> db(dataSource, call) { it.createUnit(request, user.userId) } } }
        put("/collection-units/{id}") { val request = call.receive<CollectionUnitRequest>(); withUser(auth, call, Permission.MANAGE_WORKDAYS) { user -> db(dataSource, call) { it.updateUnit(requireId(call), request, user.userId) } } }
        post("/collection-units/{id}/activate") { withUser(auth, call, Permission.MANAGE_WORKDAYS) { user -> db(dataSource, call) { it.changeStatus("collection_unit", requireId(call), "ACTIVE", user.userId, "COLLECTION_UNIT") } } }
        post("/collection-units/{id}/deactivate") { withUser(auth, call, Permission.MANAGE_WORKDAYS) { user -> db(dataSource, call) { it.changeStatus("collection_unit", requireId(call), "INACTIVE", user.userId, "COLLECTION_UNIT") } } }
        get("/workdays") { withUser(auth, call, Permission.VIEW_WORKDAYS) { db(dataSource, call) { it.workdays(call.request.queryParameters["date"], call.request.queryParameters["routeId"], call.request.queryParameters["unitId"]) } } }
        post("/workdays") { val request = call.receive<WorkdayRequest>(); withUser(auth, call, Permission.MANAGE_WORKDAYS) { user -> db(dataSource, call) { it.createWorkday(request, user.userId) } } }
        get("/workdays/{id}") { withUser(auth, call, Permission.VIEW_WORKDAYS) { db(dataSource, call) { it.workday(requireId(call)) } } }
        put("/workdays/{id}") { val request = call.receive<WorkdayRequest>(); withUser(auth, call, Permission.MANAGE_WORKDAYS) { user -> db(dataSource, call) { it.updateWorkday(requireId(call), request, user.userId) } } }
        post("/workdays/{id}/cancel") { withUser(auth, call, Permission.MANAGE_WORKDAYS) { user -> db(dataSource, call) { it.changeStatus("collection_workday", requireId(call), "CANCELLED", user.userId, "WORKDAY") } } }
        post("/workdays/{id}/staff") { val request = call.receive<WorkdayStaffRequest>(); withUser(auth, call, Permission.MANAGE_WORKDAYS) { user -> db(dataSource, call) { it.assignStaff(requireId(call), request, user.userId) } } }
        get("/workdays/{id}/staff") { withUser(auth, call, Permission.VIEW_WORKDAYS) { db(dataSource, call) { it.staff(requireId(call)) } } }
        delete("/workdays/{id}/staff/{userId}") { withUser(auth, call, Permission.MANAGE_WORKDAYS) { user -> db(dataSource, call) { it.removeStaff(requireId(call), call.parameters["userId"]!!, user.userId) } } }

        get("/catalog/products") { withUser(auth, call, Permission.VIEW_CATALOG) { db(dataSource, call) { it.simple("product") } } }
        get("/catalog/products/{id}") { withUser(auth, call, Permission.VIEW_CATALOG) { db(dataSource, call) { it.catalog("product", requireId(call)) } } }
        post("/catalog/products") { val request = call.receive<ProductRequest>(); withUser(auth, call, Permission.MANAGE_CATALOG) { user -> db(dataSource, call) { it.createProduct(request, user.userId) } } }
        put("/catalog/products/{id}") { val request = call.receive<ProductRequest>(); withUser(auth, call, Permission.MANAGE_CATALOG) { user -> db(dataSource, call) { it.updateCatalog("product", requireId(call), request.code, request.name, user.userId) } } }
        post("/catalog/products/{id}/deactivate") { withUser(auth, call, Permission.MANAGE_CATALOG) { user -> db(dataSource, call) { it.changeStatus("product", requireId(call), "INACTIVE", user.userId, "PRODUCT") } } }
        post("/catalog/products/{id}/activate") { withUser(auth, call, Permission.MANAGE_CATALOG) { user -> db(dataSource, call) { it.changeStatus("product", requireId(call), "ACTIVE", user.userId, "PRODUCT") } } }
        get("/catalog/customers") { withUser(auth, call, Permission.VIEW_CATALOG) { db(dataSource, call) { it.simple("customer") } } }
        get("/catalog/customers/{id}") { withUser(auth, call, Permission.VIEW_CATALOG) { db(dataSource, call) { it.catalog("customer", requireId(call)) } } }
        post("/catalog/customers") { val request = call.receive<CustomerRequest>(); withUser(auth, call, Permission.MANAGE_CATALOG) { user -> db(dataSource, call) { it.createCustomer(request, user.userId) } } }
        put("/catalog/customers/{id}") { val request = call.receive<CustomerRequest>(); withUser(auth, call, Permission.MANAGE_CATALOG) { user -> db(dataSource, call) { it.updateCatalog("customer", requireId(call), request.code, request.name, user.userId) } } }
        post("/catalog/customers/{id}/deactivate") { withUser(auth, call, Permission.MANAGE_CATALOG) { user -> db(dataSource, call) { it.changeStatus("customer", requireId(call), "INACTIVE", user.userId, "CUSTOMER") } } }
        post("/catalog/customers/{id}/activate") { withUser(auth, call, Permission.MANAGE_CATALOG) { user -> db(dataSource, call) { it.changeStatus("customer", requireId(call), "ACTIVE", user.userId, "CUSTOMER") } } }
        post("/catalog/prices") { val request = call.receive<PriceRequest>(); withUser(auth, call, Permission.MANAGE_CATALOG) { user -> db(dataSource, call) { it.createPrice(request, user.userId) } } }
        get("/catalog/prices/{productId}") { withUser(auth, call, Permission.VIEW_CATALOG) { db(dataSource, call) { it.prices(requireId(call)) } } }
        get("/catalog/prices/{productId}/resolve") { withUser(auth, call, Permission.VIEW_CATALOG) { db(dataSource, call) { it.resolvePrice(requireId(call), call.request.queryParameters["customerType"] ?: "PUBLIC", call.request.queryParameters["date"] ?: LocalDate.now().toString()) } } }
        post("/catalog/prices/{id}/deactivate") { withUser(auth, call, Permission.MANAGE_CATALOG) { user -> db(dataSource, call) { it.changeStatus("product_price", requireId(call), "INACTIVE", user.userId, "PRICE") } } }
        post("/catalog/prices/{id}/close") { withUser(auth, call, Permission.MANAGE_CATALOG) { user -> db(dataSource, call) { it.closePrice(requireId(call), user.userId) } } }

        get("/parameters") { withUser(auth, call, Permission.VIEW_PARAMETERS) { db(dataSource, call) { it.parameters() } } }
        post("/parameters") { val request = call.receive<ParameterRequest>(); withUser(auth, call, Permission.MANAGE_PARAMETERS) { user -> db(dataSource, call) { it.createParameter(request, user.userId) } } }
        get("/parameters/{key}") { withUser(auth, call, Permission.VIEW_PARAMETERS) { db(dataSource, call) { it.parameterHistory(call.parameters["key"]!!) } } }
        post("/parameters/{key}/deactivate") { withUser(auth, call, Permission.MANAGE_PARAMETERS) { user -> db(dataSource, call) { it.deactivateParameter(call.parameters["key"]!!, user.userId) } } }
        get("/audit") { withUser(auth, call, Permission.VIEW_AUDIT) { db(dataSource, call) { it.audit(call.request.queryParameters["actor"], call.request.queryParameters["action"], call.request.queryParameters["entityType"], call.request.queryParameters["entityId"], call.request.queryParameters["page"]?.toIntOrNull() ?: 0, call.request.queryParameters["pageSize"]?.toIntOrNull() ?: 50) } } }
        get("/reports/operational") { withUser(auth, call, Permission.VIEW_REPORTS) { db(dataSource, call) { it.report(call.request.queryParameters["dateFrom"], call.request.queryParameters["dateTo"], call.request.queryParameters["providerId"], call.request.queryParameters["zoneId"], call.request.queryParameters["routeId"]) } } }
    }
}

private suspend fun withUser(auth: AuthService?, call: ApplicationCall, permission: Permission, allowSelf: Boolean = false, block: suspend (AuthenticatedUser) -> Unit) {
    if (auth == null) { call.respond(HttpStatusCode.ServiceUnavailable, ApiEnvelope<Unit>(error = pe.gob.huata.ecolactea.core.network.ApiErrorDto("UNAVAILABLE", "Servicio no disponible"))); return }
    val result = withContext(Dispatchers.IO) { auth.me(call.token()) }
    val user = (result as? AppResult.Success)?.value
    val permitted = user != null && (pe.gob.huata.ecolactea.core.model.Authorization.allows(user, permission) || (allowSelf && user.role.name == "PROVEEDOR"))
    if (!permitted) { forbidden(call); return }
    block(user)
}
private suspend fun forbidden(call: ApplicationCall) = call.respond(HttpStatusCode.Forbidden, ApiEnvelope<Unit>(error = pe.gob.huata.ecolactea.core.network.ApiErrorDto("FORBIDDEN", "No tienes permiso para esta operación")))
private fun ApplicationCall.token() = request.headers[HttpHeaders.Authorization]?.removePrefix("Bearer ").orEmpty()
private fun requireId(call: ApplicationCall) = requireNotNull(call.parameters["id"] ?: call.parameters["productId"])
private suspend fun <T> db(dataSource: DataSource?, call: ApplicationCall, block: (OperationsRepository) -> T) {
    if (dataSource == null) { call.respond(HttpStatusCode.ServiceUnavailable, ApiEnvelope<Unit>(error = pe.gob.huata.ecolactea.core.network.ApiErrorDto("UNAVAILABLE", "Base de datos no configurada"))); return }
    try { call.respond(ApiEnvelope(data = withContext(Dispatchers.IO) { block(OperationsRepository(dataSource)) })) }
    catch (e: IllegalArgumentException) { call.respond(HttpStatusCode.BadRequest, ApiEnvelope<Unit>(error = pe.gob.huata.ecolactea.core.network.ApiErrorDto("VALIDATION", e.message ?: "Solicitud inválida"))) }
    catch (e: IllegalStateException) { call.respond(HttpStatusCode.NotFound, ApiEnvelope<Unit>(error = pe.gob.huata.ecolactea.core.network.ApiErrorDto("NOT_FOUND", e.message ?: "Recurso no encontrado"))) }
    catch (_: java.sql.SQLIntegrityConstraintViolationException) { call.respond(HttpStatusCode.Conflict, ApiEnvelope<Unit>(error = pe.gob.huata.ecolactea.core.network.ApiErrorDto("CONFLICT", "La operación entra en conflicto con datos existentes"))) }
}

private class OperationsRepository(private val source: DataSource) {
    private fun <T> tx(block: (Connection) -> T): T = source.connection.use { c -> c.autoCommit = false; try { block(c).also { c.commit() } } catch (e: Exception) { c.rollback(); throw e } }
    private fun audit(c: Connection, actor: String, action: String, type: String, id: String, after: String? = null, reason: String? = null) = c.prepareStatement("INSERT INTO audit_event(id,actor_user_id,action,entity_type,entity_id,after_data,reason) VALUES (?,?,?,?,?,?,?)").use { s -> s.setString(1, UUID.randomUUID().toString()); s.setString(2, actor); s.setString(3, action); s.setString(4, type); s.setString(5, id); s.setString(6, after); s.setString(7, reason); s.executeUpdate() }
    fun providers(): List<ProviderDto> = source.connection.use { c -> c.prepareStatement("SELECT id,code,dni,first_name,last_name,phone,farm_name,status FROM provider ORDER BY last_name,first_name").use { s -> s.executeQuery().use { r -> buildList { while (r.next()) add(provider(r)) } } } }
    fun provider(id: String): ProviderDto = source.connection.use { c -> c.prepareStatement("SELECT id,code,dni,first_name,last_name,phone,farm_name,status FROM provider WHERE id=?").use { s -> s.setString(1,id); s.executeQuery().use { r -> check(r.next()) { "Proveedor inexistente" }; provider(r) } } }
    private fun provider(r: java.sql.ResultSet) = ProviderDto(r.getString(1),r.getString(2),r.getString(3),r.getString(4),r.getString(5),r.getString(6),r.getString(7),r.getString(8))
    fun createProvider(req: ProviderRequest, actor: String): ProviderDto = tx { c -> require(req.dni.isNotBlank() && req.firstName.isNotBlank() && req.lastName.isNotBlank()); val id=UUID.randomUUID().toString(); val code="PRV-${id.substring(0,8).uppercase()}"; c.prepareStatement("INSERT INTO provider(id,code,dni,first_name,last_name,phone,farm_name,status) VALUES(?,?,?,?,?,?,?, 'ACTIVE')").use { s -> listOf(id,code,req.dni.trim(),req.firstName.trim(),req.lastName.trim(),req.phone.trim(),req.farmName).forEachIndexed { i,v -> s.setString(i+1,v) }; s.executeUpdate() }; audit(c,actor,"CREATE","PROVIDER",id,"{\"dni\":\"${req.dni}\"}"); ProviderDto(id,code,req.dni,req.firstName,req.lastName,req.phone,req.farmName,"ACTIVE") }
    fun updateProvider(id: String, req: ProviderRequest, actor: String): ProviderDto = tx { c -> c.prepareStatement("UPDATE provider SET dni=?,first_name=?,last_name=?,phone=?,farm_name=?,version=version+1 WHERE id=?").use { s -> s.setString(1,req.dni);s.setString(2,req.firstName);s.setString(3,req.lastName);s.setString(4,req.phone);s.setString(5,req.farmName);s.setString(6,id);check(s.executeUpdate()==1) { "Proveedor inexistente" } }; audit(c,actor,"UPDATE","PROVIDER",id); c.prepareStatement("SELECT code,status FROM provider WHERE id=?").use { s -> s.setString(1,id);s.executeQuery().use { r -> r.next(); ProviderDto(id,r.getString(1),req.dni,req.firstName,req.lastName,req.phone,req.farmName,r.getString(2)) } } }
    fun createZone(req: ZoneRequest, actor: String) = tx { c -> val id=UUID.randomUUID().toString(); c.prepareStatement("INSERT INTO zone(id,code,name,description,status) VALUES(?,?,?,?, 'ACTIVE')").use { s -> s.setString(1,id);s.setString(2,req.code);s.setString(3,req.name);s.setString(4,req.description);s.executeUpdate() }; audit(c,actor,"CREATE","ZONE",id); SimpleRow(id,req.code,req.name,"ACTIVE") }
    fun updateZone(id: String, req: ZoneRequest, actor: String) = tx { c -> c.prepareStatement("UPDATE zone SET code=?,name=?,description=?,version=version+1 WHERE id=?").use { s -> s.setString(1,req.code);s.setString(2,req.name);s.setString(3,req.description);s.setString(4,id);check(s.executeUpdate()==1) { "Zona inexistente" } }; audit(c,actor,"UPDATE","ZONE",id); SimpleRow(id,req.code,req.name,"ACTIVE") }
    fun createRoute(req: RouteRequest, actor: String) = tx { c -> Date.valueOf(req.validFrom); c.prepareStatement("SELECT id FROM zone WHERE id=? AND status='ACTIVE'").use { s -> s.setString(1,req.zoneId); check(s.executeQuery().next()) { "Zona inexistente o inactiva" } }; val id=UUID.randomUUID().toString(); c.prepareStatement("INSERT INTO route(id,code,name,zone_id,description,status,valid_from) VALUES(?,?,?,?,?,'ACTIVE',?)").use { s -> s.setString(1,id);s.setString(2,req.code);s.setString(3,req.name);s.setString(4,req.zoneId);s.setString(5,req.description);s.setDate(6,Date.valueOf(req.validFrom));s.executeUpdate() }; audit(c,actor,"CREATE","ROUTE",id); SimpleRow(id,req.code,req.name,"ACTIVE") }
    fun updateRoute(id: String, req: RouteRequest, actor: String) = tx { c -> c.prepareStatement("UPDATE route SET code=?,name=?,zone_id=?,description=?,valid_from=?,version=version+1 WHERE id=?").use { s -> s.setString(1,req.code);s.setString(2,req.name);s.setString(3,req.zoneId);s.setString(4,req.description);s.setDate(5,Date.valueOf(req.validFrom));s.setString(6,id);check(s.executeUpdate()==1) { "Ruta inexistente" } }; audit(c,actor,"UPDATE","ROUTE",id); SimpleRow(id,req.code,req.name,"ACTIVE") }
    fun assign(providerId: String, req: AssignmentRequest, actor: String) = tx { c -> c.prepareStatement("SELECT id FROM provider WHERE id=? AND status='ACTIVE'").use { s -> s.setString(1,providerId);check(s.executeQuery().next()) { "Proveedor inexistente o inactivo" } }; c.prepareStatement("SELECT id FROM route WHERE id=? AND status='ACTIVE'").use { s -> s.setString(1,req.routeId);check(s.executeQuery().next()) { "Ruta inexistente o inactiva" } }; c.prepareStatement("UPDATE provider_route_assignment SET valid_to=DATE_SUB(?, INTERVAL 1 DAY), status='CLOSED' WHERE provider_id=? AND status='ACTIVE' AND (valid_to IS NULL OR valid_to>=?)").use { s -> val d=Date.valueOf(req.validFrom);s.setDate(1,d);s.setString(2,providerId);s.setDate(3,d);s.executeUpdate() }; val id=UUID.randomUUID().toString(); c.prepareStatement("INSERT INTO provider_route_assignment(id,provider_id,route_id,valid_from,status,created_by,reason) VALUES(?,?,?,?, 'ACTIVE',?,?)").use { s -> s.setString(1,id);s.setString(2,providerId);s.setString(3,req.routeId);s.setDate(4,Date.valueOf(req.validFrom));s.setString(5,actor);s.setString(6,req.reason);s.executeUpdate() }; audit(c,actor,"ASSIGN","PROVIDER_ROUTE",id,reason=req.reason); SimpleRow(id,req.routeId,req.validFrom,"ACTIVE") }
    fun history(id: String): HistoryDto = tx { c ->
        val p=provider(id)
        val a=rows(c,"SELECT id,route_id,route_id,status FROM provider_route_assignment WHERE provider_id=? ORDER BY valid_from DESC",id)
        val collections=rows(c,"SELECT id,'FIELD',CAST(liters AS CHAR),status FROM milk_collection WHERE provider_id=? ORDER BY collected_at DESC",id)
        val direct=rows(c,"SELECT id,'DIRECT_DELIVERY',CAST(liters AS CHAR),status FROM direct_delivery WHERE provider_id=? ORDER BY delivered_at DESC",id)
        val quality=rows(c,"SELECT id,source_type,source_id,status FROM quality_analysis WHERE provider_id=? ORDER BY analyzed_at DESC",id)
        val incidents=rows(c,"SELECT id,category,severity,status FROM quality_incident WHERE provider_id=? ORDER BY occurred_at DESC",id)
        val summaries=rows(c,"SELECT cp.closure_id,CONCAT(w.week_start,'/',w.week_end),CAST(cp.total_liters AS CHAR),w.status FROM weekly_collection_closure_provider cp JOIN weekly_collection_closure w ON w.id=cp.closure_id WHERE cp.provider_id=? ORDER BY w.week_start DESC",id)
        val settlements=rows(c,"SELECT s.id,s.weekly_closure_id,CONCAT('total=',s.net_amount,',paid=',COALESCE(SUM(CASE WHEN pay.status='CONFIRMED' THEN pay.amount ELSE 0 END),0),',balance=',s.net_amount-COALESCE(SUM(CASE WHEN pay.status='CONFIRMED' THEN pay.amount ELSE 0 END),0)),s.status FROM settlement s LEFT JOIN payment pay ON pay.settlement_id=s.id WHERE s.provider_id=? GROUP BY s.id,s.weekly_closure_id,s.net_amount,s.status,s.calculated_at ORDER BY s.calculated_at DESC",id)
        val payments=rows(c,"SELECT id,method,CONCAT(CAST(amount AS CHAR),' @ ',paid_at),status FROM payment WHERE provider_id=? ORDER BY paid_at DESC",id)
        HistoryDto(p,a,collections,direct,quality,incidents,summaries,settlements,payments)
    }
    fun simple(table: String): List<SimpleRow> = source.connection.use { c -> val nameColumn = if (table == "collection_unit") "description" else if (table == "collection_workday") "DATE_FORMAT(work_date,'%Y-%m-%d')" else "name"; c.prepareStatement("SELECT id,code,$nameColumn,status FROM $table ORDER BY code").use { s -> s.executeQuery().use { r -> buildList { while(r.next())add(SimpleRow(r.getString(1),r.getString(2),r.getString(3),r.getString(4))) } } } }
    fun workdays(date: String?, routeId: String?, unitId: String?): List<SimpleRow> = source.connection.use { c -> val filters=buildList { if(date!=null)add("work_date=?");if(routeId!=null)add("route_id=?");if(unitId!=null)add("unit_id=?") }; val sql="SELECT id,code,DATE_FORMAT(work_date,'%Y-%m-%d'),status FROM collection_workday ${if(filters.isEmpty())"" else "WHERE "+filters.joinToString(" AND ")} ORDER BY work_date,planned_start_time"; c.prepareStatement(sql).use { s -> var i=1;date?.let { s.setDate(i++,Date.valueOf(it)) };routeId?.let { s.setString(i++,it) };unitId?.let { s.setString(i,it) };s.executeQuery().use { r -> buildList { while(r.next())add(SimpleRow(r.getString(1),r.getString(2),r.getString(3),r.getString(4))) } } } }
    fun catalog(table: String, id: String): SimpleRow = source.connection.use { c -> require(table=="product" || table=="customer"); c.prepareStatement("SELECT id,code,name,status FROM $table WHERE id=?").use { s -> s.setString(1,id);s.executeQuery().use { r -> check(r.next()) { "Registro inexistente" };SimpleRow(r.getString(1),r.getString(2),r.getString(3),r.getString(4)) } } }
    fun simpleRoutes(zoneId: String? = null): List<SimpleRow> = source.connection.use { c -> c.prepareStatement("SELECT id,code,name,status FROM route ${if(zoneId == null) "" else "WHERE zone_id=?"} ORDER BY code").use { s -> if(zoneId != null)s.setString(1,zoneId);s.executeQuery().use { r -> buildList { while(r.next())add(SimpleRow(r.getString(1),r.getString(2),r.getString(3),r.getString(4))) } } } }
    fun createUnit(req: CollectionUnitRequest, actor: String) = tx { c -> require(req.code.isNotBlank() && req.description.isNotBlank()); val id=UUID.randomUUID().toString(); c.prepareStatement("INSERT INTO collection_unit(id,code,plate_or_identifier,description,status) VALUES(?,?,?,?,'ACTIVE')").use { s -> s.setString(1,id);s.setString(2,req.code);s.setString(3,req.plateOrIdentifier);s.setString(4,req.description);s.executeUpdate() }; audit(c,actor,"UNIT_CREATED","COLLECTION_UNIT",id); SimpleRow(id,req.code,req.description,"ACTIVE") }
    fun updateUnit(id: String, req: CollectionUnitRequest, actor: String) = tx { c -> c.prepareStatement("UPDATE collection_unit SET code=?,plate_or_identifier=?,description=?,version=version+1 WHERE id=?").use { s -> s.setString(1,req.code);s.setString(2,req.plateOrIdentifier);s.setString(3,req.description);s.setString(4,id);check(s.executeUpdate()==1) { "Unidad inexistente" } }; audit(c,actor,"UNIT_UPDATED","COLLECTION_UNIT",id); SimpleRow(id,req.code,req.description,"ACTIVE") }
    fun createWorkday(req: WorkdayRequest, actor: String) = tx { c -> validateWorkday(c, req); val id=UUID.randomUUID().toString(); c.prepareStatement("INSERT INTO collection_workday(id,code,route_id,unit_id,work_date,planned_start_time,planned_end_time,status,created_by) VALUES(?,?,?,?,?,?,?,'PLANNED',?)").use { s -> s.setString(1,id);s.setString(2,req.code);s.setString(3,req.routeId);s.setString(4,req.unitId);s.setDate(5,Date.valueOf(req.workDate));s.setString(6,req.plannedStartTime);s.setString(7,req.plannedEndTime);s.setString(8,actor);s.executeUpdate() }; audit(c,actor,"CREATE","WORKDAY",id); SimpleRow(id,req.code,req.workDate,"PLANNED") }
    private fun validateWorkday(c: Connection, req: WorkdayRequest, ignoreId: String? = null) { require(req.plannedEndTime == null || req.plannedStartTime < req.plannedEndTime) { "Horario inválido" }; c.prepareStatement("SELECT id FROM route WHERE id=? AND status='ACTIVE'").use { s -> s.setString(1,req.routeId);check(s.executeQuery().next()) { "Ruta inexistente o inactiva" } }; c.prepareStatement("SELECT id FROM collection_unit WHERE id=? AND status='ACTIVE'").use { s -> s.setString(1,req.unitId);check(s.executeQuery().next()) { "Unidad inexistente o inactiva" } }; c.prepareStatement("SELECT id FROM collection_workday WHERE unit_id=? AND work_date=? AND status IN ('PLANNED','ACTIVE') AND id<>COALESCE(?, '') AND planned_start_time < COALESCE(?, '23:59:59') AND COALESCE(planned_end_time, '23:59:59') > ?").use { s -> s.setString(1,req.unitId);s.setDate(2,Date.valueOf(req.workDate));s.setString(3,ignoreId);s.setString(4,req.plannedEndTime);s.setString(5,req.plannedStartTime);check(!s.executeQuery().next()) { "La unidad tiene una jornada solapada" } } }
    fun workday(id: String): SimpleRow = source.connection.use { c -> c.prepareStatement("SELECT id,code,DATE_FORMAT(work_date,'%Y-%m-%d'),status FROM collection_workday WHERE id=?").use { s -> s.setString(1,id);s.executeQuery().use { r -> check(r.next()) { "Jornada inexistente" }; SimpleRow(r.getString(1),r.getString(2),r.getString(3),r.getString(4)) } } }
    fun updateWorkday(id: String, req: WorkdayRequest, actor: String) = tx { c -> validateWorkday(c,req,id); c.prepareStatement("UPDATE collection_workday SET code=?,route_id=?,unit_id=?,work_date=?,planned_start_time=?,planned_end_time=?,version=version+1 WHERE id=? AND status<>'CANCELLED'").use { s -> s.setString(1,req.code);s.setString(2,req.routeId);s.setString(3,req.unitId);s.setDate(4,Date.valueOf(req.workDate));s.setString(5,req.plannedStartTime);s.setString(6,req.plannedEndTime);s.setString(7,id);check(s.executeUpdate()==1) { "Jornada inexistente o cancelada" } }; audit(c,actor,"UPDATE","WORKDAY",id); SimpleRow(id,req.code,req.workDate,"PLANNED") }
    fun assignStaff(workdayId: String, req: WorkdayStaffRequest, actor: String) = tx { c -> c.prepareStatement("SELECT id FROM app_user WHERE id=? AND active=TRUE AND role_code IN ('PERSONAL_PLANTA','ACOPIADOR')").use { s -> s.setString(1,req.userId);check(s.executeQuery().next()) { "Personal inexistente o inactivo" } }; c.prepareStatement("SELECT 1 FROM collection_workday_staff ws JOIN collection_workday w ON w.id=ws.workday_id JOIN collection_workday nw ON nw.id=? WHERE ws.user_id=? AND ws.workday_id<>nw.id AND w.work_date=nw.work_date AND w.status IN ('PLANNED','ACTIVE') AND nw.status IN ('PLANNED','ACTIVE') AND w.planned_start_time < COALESCE(nw.planned_end_time,'23:59:59') AND COALESCE(w.planned_end_time,'23:59:59') > nw.planned_start_time").use { s -> s.setString(1,workdayId);s.setString(2,req.userId);check(!s.executeQuery().next()) { "El personal ya está asignado a una jornada solapada" } }; c.prepareStatement("INSERT INTO collection_workday_staff(workday_id,user_id,responsibility) VALUES(?,?,?) ON DUPLICATE KEY UPDATE responsibility=VALUES(responsibility)").use { s -> s.setString(1,workdayId);s.setString(2,req.userId);s.setString(3,req.responsibility);s.executeUpdate() }; audit(c,actor,"WORKDAY_STAFF_ASSIGNED","WORKDAY",workdayId); SimpleRow(workdayId,req.userId,req.responsibility,"ASSIGNED") }
    fun staff(workdayId: String): List<SimpleRow> = source.connection.use { c -> c.prepareStatement("SELECT u.id,u.username,ws.responsibility,CASE WHEN u.active THEN 'ACTIVE' ELSE 'INACTIVE' END FROM collection_workday_staff ws JOIN app_user u ON u.id=ws.user_id WHERE ws.workday_id=? ORDER BY u.username").use { s -> s.setString(1,workdayId);s.executeQuery().use { r -> buildList { while(r.next()) add(SimpleRow(r.getString(1),r.getString(2),r.getString(3),r.getString(4))) } } } }
    fun removeStaff(workdayId: String, userId: String, actor: String) = tx { c -> c.prepareStatement("DELETE FROM collection_workday_staff WHERE workday_id=? AND user_id=?").use { s -> s.setString(1,workdayId);s.setString(2,userId);check(s.executeUpdate()==1) { "Personal no asignado" } }; audit(c,actor,"WORKDAY_STAFF_REMOVED","WORKDAY",workdayId); SimpleRow(workdayId,userId,"","REMOVED") }
    fun changeStatus(table: String, id: String, status: String, actor: String, type: String): SimpleRow = tx { c -> val allowed = setOf("provider","zone","route","collection_unit","collection_workday","product","customer","product_price"); require(table in allowed); c.prepareStatement("UPDATE $table SET status=? WHERE id=?").use { s -> s.setString(1,status);s.setString(2,id);check(s.executeUpdate()==1) { "Registro inexistente" } }; audit(c,actor,if(status=="ACTIVE") "ACTIVATE" else if(status=="CANCELLED") "CANCEL" else "DEACTIVATE",type,id); SimpleRow(id,id,"",status) }
    fun updateCatalog(table: String, id: String, code: String, name: String, actor: String) = tx { c -> require(table=="product" || table=="customer"); c.prepareStatement("UPDATE $table SET code=?,name=?,version=version+1 WHERE id=?").use { s -> s.setString(1,code);s.setString(2,name);s.setString(3,id);check(s.executeUpdate()==1) { "Registro inexistente" } }; audit(c,actor,"UPDATE",table.uppercase(),id); SimpleRow(id,code,name,"ACTIVE") }
    fun createProduct(req: ProductRequest, actor: String) = tx { c -> require(req.code.isNotBlank() && req.name.isNotBlank() && req.unit.isNotBlank()); val id=UUID.randomUUID().toString(); c.prepareStatement("INSERT INTO product(id,code,name,category,unit,status) VALUES(?,?,?,?,?,'ACTIVE')").use { s -> s.setString(1,id);s.setString(2,req.code);s.setString(3,req.name);s.setString(4,req.category);s.setString(5,req.unit);s.executeUpdate() }; audit(c,actor,"PRODUCT_CREATED","PRODUCT",id); SimpleRow(id,req.code,req.name,"ACTIVE") }
    fun createCustomer(req: CustomerRequest, actor: String) = tx { c -> require(req.code.isNotBlank() && req.name.isNotBlank() && req.customerType in setOf("WHOLESALE","PROVIDER","PUBLIC")); val id=UUID.randomUUID().toString(); c.prepareStatement("INSERT INTO customer(id,code,name,document,customer_type,phone,status) VALUES(?,?,?,?,?,?, 'ACTIVE')").use { s -> s.setString(1,id);s.setString(2,req.code);s.setString(3,req.name);s.setString(4,req.document);s.setString(5,req.customerType);s.setString(6,req.phone);s.executeUpdate() }; audit(c,actor,"CUSTOMER_CREATED","CUSTOMER",id); SimpleRow(id,req.code,req.name,"ACTIVE") }
    fun createPrice(req: PriceRequest, actor: String) = tx { c -> val amount=BigDecimal(req.amount); require(amount > BigDecimal.ZERO) { "El importe debe ser mayor que cero" }; val from=Date.valueOf(req.effectiveFrom); val to=req.effectiveTo?.let(Date::valueOf); require(to == null || to.after(from)) { "effectiveTo debe ser posterior a effectiveFrom" }; c.prepareStatement("SELECT id FROM product_price WHERE product_id=? AND customer_type=? AND status='ACTIVE' AND effective_from < COALESCE(?, '9999-12-31') AND (effective_to IS NULL OR effective_to > ?)").use { s -> s.setString(1,req.productId);s.setString(2,req.customerType);s.setDate(3,to);s.setDate(4,from);check(!s.executeQuery().next()) { "Vigencia de precio solapada" } }; val id=UUID.randomUUID().toString(); c.prepareStatement("INSERT INTO product_price(id,product_id,customer_type,amount,currency,effective_from,effective_to,status,created_by,reason) VALUES(?,?,?,?,?,?,?,'ACTIVE',?,?)").use { s -> s.setString(1,id);s.setString(2,req.productId);s.setString(3,req.customerType);s.setBigDecimal(4,amount);s.setString(5,req.currency);s.setDate(6,from);s.setDate(7,to);s.setString(8,actor);s.setString(9,req.reason);s.executeUpdate() }; audit(c,actor,if(to==null)"PRICE_CREATED" else "PRICE_SCHEDULED","PRODUCT_PRICE",id,reason=req.reason); SimpleRow(id,req.productId,amount.toPlainString(),"ACTIVE") }
    fun prices(productId: String): List<SimpleRow> = source.connection.use { c -> c.prepareStatement("SELECT id,product_id,amount,status FROM product_price WHERE product_id=? ORDER BY effective_from DESC").use { s -> s.setString(1,productId);s.executeQuery().use { r -> buildList { while(r.next())add(SimpleRow(r.getString(1),r.getString(2),r.getBigDecimal(3).toPlainString(),r.getString(4))) } } } }
    fun resolvePrice(productId: String, customerType: String, date: String): SimpleRow = source.connection.use { c -> c.prepareStatement("SELECT id,product_id,amount,status FROM product_price WHERE product_id=? AND customer_type=? AND status='ACTIVE' AND effective_from<=? AND (effective_to IS NULL OR effective_to>=?) ORDER BY effective_from DESC LIMIT 1").use { s -> val d=Date.valueOf(date);s.setString(1,productId);s.setString(2,customerType);s.setDate(3,d);s.setDate(4,d);s.executeQuery().use { r -> check(r.next()) { "Precio vigente no encontrado" }; SimpleRow(r.getString(1),r.getString(2),r.getBigDecimal(3).toPlainString(),r.getString(4)) } } }
    fun closePrice(id: String, actor: String) = tx { c -> c.prepareStatement("UPDATE product_price SET effective_to=CURDATE(),status='CLOSED' WHERE id=? AND status='ACTIVE'").use { s -> s.setString(1,id);check(s.executeUpdate()==1) { "Precio vigente inexistente" } }; audit(c,actor,"PRICE_CLOSED","PRODUCT_PRICE",id); SimpleRow(id,id,"","CLOSED") }
    fun createParameter(req: ParameterRequest, actor: String) = tx { c -> val id=UUID.randomUUID().toString(); val version=c.prepareStatement("SELECT COALESCE(MAX(version),0)+1 FROM system_parameter WHERE `key`=?").use { s -> s.setString(1,req.key);s.executeQuery().use { r -> r.next();r.getLong(1) } }; c.prepareStatement("INSERT INTO system_parameter(id,`key`,value,value_type,unit,effective_from,status,version,created_by,reason) VALUES(?,?,?,?,?,?, 'PENDING_VALIDATION',?,?,?)").use { s -> s.setString(1,id);s.setString(2,req.key);s.setString(3,req.value);s.setString(4,req.valueType);s.setString(5,req.unit);s.setTimestamp(6,java.sql.Timestamp.valueOf(req.effectiveFrom.replace('T',' ')));s.setLong(7,version);s.setString(8,actor);s.setString(9,req.reason);s.executeUpdate() }; audit(c,actor,"CREATE_VERSION","SYSTEM_PARAMETER",id,reason=req.reason); SimpleRow(id,req.key,"v$version","PENDING_VALIDATION") }
    fun parameters(): List<SimpleRow> = source.connection.use { c -> c.prepareStatement("SELECT id,`key`,CONCAT('v',version),status FROM system_parameter ORDER BY `key`,version DESC").use { s -> s.executeQuery().use { r -> buildList { while(r.next())add(SimpleRow(r.getString(1),r.getString(2),r.getString(3),r.getString(4))) } } } }
    fun parameterHistory(key: String): List<SimpleRow> = source.connection.use { c -> c.prepareStatement("SELECT id,`key`,CONCAT(value,' [v',version,']'),status FROM system_parameter WHERE `key`=? ORDER BY version DESC").use { s -> s.setString(1,key);s.executeQuery().use { r -> buildList { while(r.next())add(SimpleRow(r.getString(1),r.getString(2),r.getString(3),r.getString(4))) } } } }
    fun deactivateParameter(key: String, actor: String) = tx { c -> c.prepareStatement("UPDATE system_parameter SET status='INACTIVE',effective_to=COALESCE(effective_to,CURRENT_TIMESTAMP(6)) WHERE `key`=? AND status='PENDING_VALIDATION'").use { s -> s.setString(1,key);s.executeUpdate() }; audit(c,actor,"PARAMETER_DEACTIVATED","SYSTEM_PARAMETER",key); SimpleRow(key,key,"", "INACTIVE") }
    fun audit(actor: String?, action: String?, entityType: String?, entityId: String?, page: Int, pageSize: Int): List<AuditDto> = source.connection.use { c -> val filters = listOf(actor?.let { "actor_user_id=?" }, action?.let { "action=?" }, entityType?.let { "entity_type=?" }, entityId?.let { "entity_id=?" }).filterNotNull(); val sql="SELECT id,actor_user_id,action,entity_type,entity_id,occurred_at,reason,before_data,after_data FROM audit_event ${if(filters.isEmpty()) "" else "WHERE "+filters.joinToString(" AND ")} ORDER BY occurred_at DESC LIMIT ? OFFSET ?"; c.prepareStatement(sql).use { s -> var i=1; listOf(actor,action,entityType,entityId).filterNotNull().forEach { s.setString(i++,it) }; s.setInt(i++,pageSize.coerceIn(1,200));s.setInt(i,page.coerceAtLeast(0)*pageSize.coerceIn(1,200));s.executeQuery().use { r -> buildList { while(r.next())add(AuditDto(r.getString(1),r.getString(2),r.getString(3),r.getString(4),r.getString(5),r.getTimestamp(6).toInstant().toString(),r.getString(7),r.getString(8),r.getString(9))) } } } }
    fun report(from: String?, to: String?, providerId: String?, zoneId: String?, routeId: String?) = source.connection.use { c ->
        val collections=reportRows(c,"milk_collection","collected_at","liters",from,to,providerId,routeId)
        val direct=reportRows(c,"direct_delivery","delivered_at","liters",from,to,providerId,null)
        val receptions=reportRows(c,"plant_reception","received_at","liters_received",from,to,null,routeId)
        val reconciliations=rows(c,"SELECT id,COALESCE(route_id,''),CAST(difference AS CHAR),status FROM collection_reconciliation ORDER BY created_at DESC")
        val quality=rows(c,"SELECT id,source_type,source_id,status FROM quality_analysis ORDER BY analyzed_at DESC")
        val classifications=rows(c,"SELECT id,'CLASSIFICATION',analysis_id,classification FROM quality_classification ORDER BY classified_at DESC")
        val incidents=rows(c,"SELECT id,category,severity,status FROM quality_incident ORDER BY occurred_at DESC")
        OperationalReportDto(from,to,providers(),simple("zone"),simpleRoutes(zoneId),simple("collection_workday"),collections,direct,receptions,reconciliations,quality,classifications,incidents)
    }
    private fun rows(c: Connection, sql: String, vararg args: String): List<SimpleRow> = c.prepareStatement(sql).use { s -> args.forEachIndexed { index, value -> s.setString(index + 1, value) }; s.executeQuery().use { r -> buildList { while (r.next()) add(SimpleRow(r.getString(1),r.getString(2),r.getString(3),r.getString(4))) } } }
    private fun reportRows(c: Connection, table: String, dateColumn: String, amountColumn: String, from: String?, to: String?, providerId: String?, routeId: String?): List<SimpleRow> {
        val allowed=mapOf("milk_collection" to setOf("collected_at","liters"),"direct_delivery" to setOf("delivered_at","liters"),"plant_reception" to setOf("received_at","liters_received"));require(allowed[table]?.containsAll(setOf(dateColumn,amountColumn))==true)
        val filters=buildList { if(from!=null)add("DATE($dateColumn)>=?");if(to!=null)add("DATE($dateColumn)<=?");if(providerId!=null)add("provider_id=?");if(routeId!=null)add("route_id=?") }
        val sql="SELECT id,DATE_FORMAT($dateColumn,'%Y-%m-%d'),CAST($amountColumn AS CHAR),status FROM $table ${if(filters.isEmpty())"" else "WHERE "+filters.joinToString(" AND ")} ORDER BY $dateColumn DESC LIMIT 500"
        return c.prepareStatement(sql).use { s -> var i=1;from?.let{s.setString(i++,it)};to?.let{s.setString(i++,it)};providerId?.let{s.setString(i++,it)};routeId?.let{s.setString(i,it)};s.executeQuery().use{r->buildList{while(r.next())add(SimpleRow(r.getString(1),r.getString(2),r.getString(3),r.getString(4)))}} }
    }
}
