package pe.gob.huata.ecolactea.server.quality

import com.zaxxer.hikari.HikariDataSource
import io.ktor.http.HttpHeaders
import io.ktor.http.HttpStatusCode
import io.ktor.server.application.*
import io.ktor.server.request.receive
import io.ktor.server.response.respond
import io.ktor.server.routing.*
import kotlinx.coroutines.Dispatchers
import kotlinx.coroutines.withContext
import pe.gob.huata.ecolactea.core.application.AppResult
import pe.gob.huata.ecolactea.core.model.*
import pe.gob.huata.ecolactea.core.network.*
import pe.gob.huata.ecolactea.server.auth.AuthService
import java.sql.Connection
import java.sql.Timestamp
import java.time.Instant
import java.util.UUID

fun Route.qualityRoutes(ds: HikariDataSource?, auth: AuthService?) {
    route("/api/v1") {
        post("/quality/parameters") { val r=call.receive<QualityParameterCommand>(); authz(auth,call,Permission.MANAGE_QUALITY){u->db(ds,call){it.parameter(r,u)}} }
        get("/quality/parameters") { authz(auth,call,Permission.VIEW_QUALITY){_->db(ds,call){it.parameters()}} }
        post("/quality/analyses") { val r=call.receive<QualityAnalysisCommand>(); authz(auth,call,Permission.MANAGE_QUALITY){u->db(ds,call){it.analysis(r,u)}} }
        get("/quality/analyses") { authz(auth,call,Permission.VIEW_QUALITY,true){u->db(ds,call){it.analyses(u)}} }
        get("/quality/analyses/{id}/results") { authz(auth,call,Permission.VIEW_QUALITY,true){u->db(ds,call){it.results(call.parameters["id"]!!,u)}} }
        post("/quality/analyses/{id}/results") { val r=call.receive<QualityResultCommand>(); authz(auth,call,Permission.MANAGE_QUALITY){u->db(ds,call){it.result(call.parameters["id"]!!,r,u)}} }
        post("/quality/analyses/{id}/classify") { val r=call.receive<QualityClassificationCommand>(); authz(auth,call,Permission.MANAGE_QUALITY){u->db(ds,call){it.classify(call.parameters["id"]!!,r,u)}} }
        get("/quality/incidents") { authz(auth,call,Permission.VIEW_QUALITY,true){u->db(ds,call){it.incidents(u)}} }
        post("/quality/incidents") { val r=call.receive<QualityIncidentCommand>(); authz(auth,call,Permission.MANAGE_QUALITY){u->db(ds,call){it.incident(r,u)}} }
        post("/quality/incidents/{id}/measures") { val r=call.receive<QualityMeasureCommand>(); authz(auth,call,Permission.MANAGE_QUALITY){u->db(ds,call){it.measure(call.parameters["id"]!!,r,u)}} }
        post("/quality/incidents/{id}/follow-ups") { val r=call.receive<TechnicalFollowUpCommand>(); authz(auth,call,Permission.MANAGE_QUALITY){u->db(ds,call){it.followUp(r,u)}} }
        post("/provider-notifications") { val r=call.receive<ProviderNotificationCommand>(); authz(auth,call,Permission.MANAGE_COMMUNICATIONS){u->db(ds,call){it.notification(r,u)}} }
        get("/provider-notifications") { authz(auth,call,Permission.VIEW_COMMUNICATIONS,true){u->db(ds,call){it.notifications(u)}} }
        post("/communication-events") { val r=call.receive<CommunicationEventCommand>(); authz(auth,call,Permission.MANAGE_COMMUNICATIONS){u->db(ds,call){it.event(r,u)}} }
        get("/communication-events") { authz(auth,call,Permission.VIEW_COMMUNICATIONS,true){u->db(ds,call){it.events(u)}} }
        post("/communication-events/{id}/publish") { authz(auth,call,Permission.MANAGE_COMMUNICATIONS){u->db(ds,call){it.publish(call.parameters["id"]!!,u)}} }
        post("/communication-events/{id}/attendance") { val r=call.receive<AttendanceCommand>(); authz(auth,call,Permission.MANAGE_ATTENDANCE,true){u->db(ds,call){it.attendance(call.parameters["id"]!!,r,u)}} }
        get("/communication-events/{id}/attendance") { authz(auth,call,Permission.VIEW_ATTENDANCE,true){u->db(ds,call){it.attendanceList(call.parameters["id"]!!,u)}} }
    }
}

private suspend fun authz(auth:AuthService?,call:ApplicationCall,p:Permission,self:Boolean=false,block:suspend(AuthenticatedUser)->Unit){val u=(auth?.let{withContext(Dispatchers.IO){it.me(call.request.headers[HttpHeaders.Authorization]?.removePrefix("Bearer ").orEmpty())}} as? AppResult.Success)?.value;if(u!=null&&(Authorization.allows(u,p)||(self&&u.role==Role.PROVEEDOR)))block(u)else call.respond(HttpStatusCode.Forbidden,ApiEnvelope<Unit>(error=ApiErrorDto("FORBIDDEN","No tienes permiso para esta operación")))}
private suspend fun <T> db(ds:HikariDataSource?,call:ApplicationCall,block:(QualityRepository)->T){if(ds==null){call.respond(HttpStatusCode.ServiceUnavailable,ApiEnvelope<Unit>(error=ApiErrorDto("UNAVAILABLE","Base de datos no configurada")));return};try{call.respond(ApiEnvelope(data=withContext(Dispatchers.IO){block(QualityRepository(ds))}))}catch(e:IllegalArgumentException){call.respond(HttpStatusCode.BadRequest,ApiEnvelope<Unit>(error=ApiErrorDto("VALIDATION",e.message?:"Solicitud inválida")))}catch(e:IllegalStateException){call.respond(HttpStatusCode.Conflict,ApiEnvelope<Unit>(error=ApiErrorDto("CONFLICT",e.message?:"Operación no permitida")))}}

private class QualityRepository(private val ds:HikariDataSource){
    fun parameter(r:QualityParameterCommand,u:AuthenticatedUser)=tx{c->val id=UUID.randomUUID().toString();c.prepareStatement("INSERT INTO quality_parameter(id,`key`,name,unit,value_type) VALUES(?,?,?,?,?)").use{s->s.setString(1,id);s.setString(2,r.key);s.setString(3,r.name);s.setString(4,r.unit);s.setString(5,r.valueType);s.executeUpdate()};audit(c,u.userId,"QUALITY_PARAMETER_CREATED","QUALITY_PARAMETER",id);SimpleQualityRecord(id,r.key,r.name,"ACTIVE","ACTIVE")}
    fun parameters():List<SimpleQualityRecord> = records("SELECT id,`key`,name,value_type,status FROM quality_parameter ORDER BY `key`",null)
    fun analysis(r:QualityAnalysisCommand,u:AuthenticatedUser)=tx{c->check(exists(c,"SELECT 1 FROM provider WHERE id=? AND status='ACTIVE'",r.providerId)){"Proveedor inexistente"};require(r.sourceType in setOf("MILK_COLLECTION","DIRECT_DELIVERY"));check(query(c,if(r.sourceType=="MILK_COLLECTION")"SELECT provider_id FROM milk_collection WHERE id=?" else "SELECT provider_id FROM direct_delivery WHERE id=?",r.sourceId)==r.providerId){"Fuente no pertenece al proveedor"};val id=UUID.randomUUID().toString();c.prepareStatement("INSERT INTO quality_analysis(id,provider_id,source_type,source_id,sample_reference,analyzed_at,analyst_user_id,observations) VALUES(?,?,?,?,?,?,?,?)").use{s->s.setString(1,id);s.setString(2,r.providerId);s.setString(3,r.sourceType);s.setString(4,r.sourceId);s.setString(5,r.sampleReference);s.setTimestamp(6,Timestamp.from(Instant.parse(r.analyzedAt)));s.setString(7,u.userId);s.setString(8,r.observations);s.executeUpdate()};audit(c,u.userId,"QUALITY_ANALYSIS_CREATED","QUALITY_ANALYSIS",id);SimpleQualityRecord(id,r.providerId,r.sourceType,r.sourceId,"RECORDED")}
    fun analyses(u:AuthenticatedUser)=records("SELECT id,provider_id,source_type,source_id,status FROM quality_analysis ${if(u.role==Role.PROVEEDOR)"WHERE provider_id=?" else ""} ORDER BY analyzed_at DESC LIMIT 200",u.providerId)
    fun result(id:String,r:QualityResultCommand,u:AuthenticatedUser)=tx{c->check(exists(c,"SELECT 1 FROM quality_analysis WHERE id=?",id));val p=query(c,"SELECT id FROM quality_parameter WHERE `key`=? AND status='ACTIVE'",r.parameterKey)?:error("Parámetro inexistente");val rid=UUID.randomUUID().toString();c.prepareStatement("INSERT INTO quality_test_result(id,analysis_id,parameter_id,decimal_value,text_value,unit) VALUES(?,?,?,?,?,?) ON DUPLICATE KEY UPDATE decimal_value=VALUES(decimal_value),text_value=VALUES(text_value),unit=VALUES(unit)").use{s->s.setString(1,rid);s.setString(2,id);s.setString(3,p);s.setBigDecimal(4,r.decimalValue?.toBigDecimalOrNull());s.setString(5,r.textValue);s.setString(6,r.unit);s.executeUpdate()};audit(c,u.userId,"QUALITY_RESULT_RECORDED","QUALITY_ANALYSIS",id);SimpleQualityRecord(rid,id,r.parameterKey,r.decimalValue?:r.textValue.orEmpty(),"RECORDED")}
    fun results(id:String,u:AuthenticatedUser):List<SimpleQualityRecord>{if(u.role==Role.PROVEEDOR)ds.connection.use{c->check(exists(c,"SELECT 1 FROM quality_analysis WHERE id=? AND provider_id=?",id,u.providerId)){"Análisis no disponible"}};return records("SELECT r.id,r.analysis_id,p.`key`,COALESCE(CAST(r.decimal_value AS CHAR),r.text_value),r.status FROM quality_test_result r JOIN quality_parameter p ON p.id=r.parameter_id WHERE r.analysis_id=?",id)}
    fun classify(id:String,r:QualityClassificationCommand,u:AuthenticatedUser)=tx{c->
        check(exists(c,"SELECT 1 FROM quality_analysis WHERE id=?",id)){"Análisis inexistente"}
        val measured=mutableListOf<Pair<String,java.math.BigDecimal>>()
        c.prepareStatement("SELECT p.`key`,r.decimal_value FROM quality_test_result r JOIN quality_parameter p ON p.id=r.parameter_id WHERE r.analysis_id=? AND r.decimal_value IS NOT NULL").use{s->s.setString(1,id);s.executeQuery().use{q->while(q.next())measured+=q.getString(1) to q.getBigDecimal(2)}}
        var missingRule=measured.isEmpty();var observed=false;val versions=mutableListOf<String>()
        measured.forEach{(key,value)->
            var found=false
            listOf("MIN" to false,"MAX" to true).forEach{(suffix,isMax)->
                c.prepareStatement("SELECT value,version FROM system_parameter WHERE `key`=? AND status='ACTIVE' AND effective_from<=CURRENT_TIMESTAMP(6) AND (effective_to IS NULL OR effective_to>CURRENT_TIMESTAMP(6)) ORDER BY effective_from DESC LIMIT 1").use{s->s.setString(1,"QUALITY_${key}_${suffix}");s.executeQuery().use{q->if(q.next()){val bound=q.getString(1).toBigDecimalOrNull();if(bound!=null){found=true;versions+="${key}_${suffix}:v${q.getLong(2)}";if((isMax&&value>bound)||(!isMax&&value<bound))observed=true}}}}
            }
            if(!found)missingRule=true
        }
        val status=when{missingRule->"PENDING_VALIDATION";observed->"OBSERVED";else->"APPROVED"}
        val ruleVersion=if(versions.isEmpty())"PENDING_VALIDATION" else versions.sorted().joinToString(",")
        val cid=UUID.randomUUID().toString();c.prepareStatement("INSERT INTO quality_classification(id,analysis_id,classification,rule_version,status,classified_by,observations) VALUES(?,?,?,?,?,?,?)").use{s->s.setString(1,cid);s.setString(2,id);s.setString(3,status);s.setString(4,ruleVersion);s.setString(5,status);s.setString(6,u.userId);s.setString(7,r.observations);s.executeUpdate()};audit(c,u.userId,"QUALITY_CLASSIFIED","QUALITY_CLASSIFICATION",cid);SimpleQualityRecord(cid,id,status,ruleVersion,status)}
    fun incident(r:QualityIncidentCommand,u:AuthenticatedUser)=tx{c->val id=UUID.randomUUID().toString();c.prepareStatement("INSERT INTO quality_incident(id,provider_id,analysis_id,classification_id,category,description,severity,occurred_at,created_by) VALUES(?,?,?,?,?,?,?,?,?)").use{s->s.setString(1,id);s.setString(2,r.providerId);s.setString(3,r.analysisId);s.setString(4,r.classificationId);s.setString(5,r.category);s.setString(6,r.description);s.setString(7,r.severity);s.setTimestamp(8,Timestamp.from(Instant.parse(r.occurredAt)));s.setString(9,u.userId);s.executeUpdate()};audit(c,u.userId,"QUALITY_INCIDENT_CREATED","QUALITY_INCIDENT",id);SimpleQualityRecord(id,r.providerId,r.category,r.severity,"OPEN")}
    fun incidents(u:AuthenticatedUser)=records("SELECT id,provider_id,category,severity,status FROM quality_incident ${if(u.role==Role.PROVEEDOR)"WHERE provider_id=?" else ""} ORDER BY occurred_at DESC LIMIT 200",u.providerId)
    fun measure(id:String,r:QualityMeasureCommand,u:AuthenticatedUser)=tx{c->val mid=UUID.randomUUID().toString();c.prepareStatement("INSERT INTO quality_measure(id,incident_id,measure_type,description,starts_at,ends_at,status,responsible_user_id,observations) VALUES(?,?,?,?,?,?, 'PLANNED',?,?)").use{s->s.setString(1,mid);s.setString(2,id);s.setString(3,r.measureType);s.setString(4,r.description);s.setTimestamp(5,Timestamp.from(Instant.parse(r.startsAt)));s.setTimestamp(6,r.endsAt?.let{Timestamp.from(Instant.parse(it))});s.setString(7,r.responsibleUserId);s.setString(8,r.observations);s.executeUpdate()};audit(c,u.userId,"QUALITY_MEASURE_CREATED","QUALITY_MEASURE",mid);SimpleQualityRecord(mid,id,r.measureType,"PLANNED","PLANNED")}
    fun followUp(r:TechnicalFollowUpCommand,u:AuthenticatedUser)=tx{c->val id=UUID.randomUUID().toString();c.prepareStatement("INSERT INTO technical_follow_up(id,provider_id,incident_id,follow_up_type,scheduled_at,performed_at,responsible_user_id,result,notes,status) VALUES(?,?,?,?,?,?,?,?,?,?)").use{s->s.setString(1,id);s.setString(2,r.providerId);s.setString(3,r.incidentId);s.setString(4,r.followUpType);s.setTimestamp(5,r.scheduledAt?.let{Timestamp.from(Instant.parse(it))});s.setTimestamp(6,r.performedAt?.let{Timestamp.from(Instant.parse(it))});s.setString(7,r.responsibleUserId);s.setString(8,r.result);s.setString(9,r.notes);s.setString(10,r.status);s.executeUpdate()};audit(c,u.userId,"TECHNICAL_FOLLOW_UP_CREATED","TECHNICAL_FOLLOW_UP",id);SimpleQualityRecord(id,r.providerId,r.followUpType,r.status,r.status)}
    fun notification(r:ProviderNotificationCommand,u:AuthenticatedUser)=tx{c->val id=UUID.randomUUID().toString();c.prepareStatement("INSERT INTO provider_notification(id,provider_id,notification_type,title,body,source_type,source_id,published_at,created_by) VALUES(?,?,?,?,?,?,?,?,?)").use{s->s.setString(1,id);s.setString(2,r.providerId);s.setString(3,r.notificationType);s.setString(4,r.title);s.setString(5,r.body);s.setString(6,r.sourceType);s.setString(7,r.sourceId);s.setTimestamp(8,Timestamp.from(Instant.now()));s.setString(9,u.userId);s.executeUpdate()};audit(c,u.userId,"PROVIDER_NOTIFICATION_CREATED","PROVIDER_NOTIFICATION",id);SimpleQualityRecord(id,r.providerId,r.title,"PUBLISHED","PUBLISHED")}
    fun notifications(u:AuthenticatedUser)=records("SELECT id,provider_id,title,notification_type,status FROM provider_notification WHERE provider_id=? AND status='PUBLISHED' ORDER BY published_at DESC",u.providerId)
    fun event(r:CommunicationEventCommand,u:AuthenticatedUser)=tx{c->val id=UUID.randomUUID().toString();c.prepareStatement("INSERT INTO communication_event(id,event_type,title,description,starts_at,ends_at,location,audience,created_by) VALUES(?,?,?,?,?,?,?,?,?)").use{s->s.setString(1,id);s.setString(2,r.eventType);s.setString(3,r.title);s.setString(4,r.description);s.setTimestamp(5,Timestamp.from(Instant.parse(r.startsAt)));s.setTimestamp(6,r.endsAt?.let{Timestamp.from(Instant.parse(it))});s.setString(7,r.location);s.setString(8,r.audience);s.setString(9,u.userId);s.executeUpdate()};audit(c,u.userId,"COMMUNICATION_EVENT_CREATED","COMMUNICATION_EVENT",id);SimpleQualityRecord(id,r.audience,r.title,r.description,"DRAFT")}
    fun events(u:AuthenticatedUser)=records("SELECT id,event_type,title,description,status FROM communication_event WHERE status='PUBLISHED' AND (audience='ALL' OR audience=?) ORDER BY starts_at",u.role.name)
    fun publish(id:String,u:AuthenticatedUser)=tx{c->c.prepareStatement("UPDATE communication_event SET status='PUBLISHED',published_at=CURRENT_TIMESTAMP(6) WHERE id=?").use{s->s.setString(1,id);s.executeUpdate()};audit(c,u.userId,"COMMUNICATION_EVENT_PUBLISHED","COMMUNICATION_EVENT",id);SimpleQualityRecord(id,id,"PUBLISHED","","PUBLISHED")}
    fun attendance(id:String,r:AttendanceCommand,u:AuthenticatedUser)=tx{c->val provider=if(u.role==Role.PROVEEDOR)requireNotNull(u.providerId){"Cuenta sin proveedor asociado"}else r.providerId;c.prepareStatement("INSERT INTO event_attendance(event_id,provider_id,status,marked_by,marking_method) VALUES(?,?,?,?,?) ON DUPLICATE KEY UPDATE status=VALUES(status),marked_at=CURRENT_TIMESTAMP(6)").use{s->s.setString(1,id);s.setString(2,provider);s.setString(3,r.status);s.setString(4,u.userId);s.setString(5,r.markingMethod);s.executeUpdate()};audit(c,u.userId,"EVENT_ATTENDANCE_MARKED","COMMUNICATION_EVENT",id);SimpleQualityRecord(id,provider,r.status,r.markingMethod,r.status)}
    fun attendanceList(id:String,u:AuthenticatedUser):List<SimpleQualityRecord> = ds.connection.use{c->val own=u.role==Role.PROVEEDOR;val sql="SELECT event_id,provider_id,status,marking_method,status FROM event_attendance WHERE event_id=? ${if(own)"AND provider_id=?" else ""}";c.prepareStatement(sql).use{s->s.setString(1,id);if(own)s.setString(2,requireNotNull(u.providerId));s.executeQuery().use{q->buildList{while(q.next())add(SimpleQualityRecord(q.getString(1),q.getString(2),q.getString(3),q.getString(4),q.getString(5)))}}}}
    private fun insertSimple(table:String,subject:String,name:String,status:String,actor:String,action:String)=tx{c->val id=UUID.randomUUID().toString();audit(c,actor,action,table.uppercase(),id);SimpleQualityRecord(id,subject,name,status,status)}
    private fun records(sql:String,subject:String?):List<SimpleQualityRecord> = ds.connection.use{c->c.prepareStatement(sql).use{s->if(sql.contains("?")){if(subject==null)s.setNull(1,java.sql.Types.VARCHAR)else s.setString(1,subject)};s.executeQuery().use{q->buildList{while(q.next())add(SimpleQualityRecord(q.getString(1),q.getString(2),q.getString(3),q.getString(4),q.getString(5)))}}}}
    private fun exists(c:Connection,sql:String,vararg a:String?):Boolean=c.prepareStatement(sql).use{s->a.forEachIndexed{i,v->if(v==null)s.setNull(i+1,java.sql.Types.VARCHAR)else s.setString(i+1,v)};s.executeQuery().use{it.next()}}
    private fun query(c:Connection,sql:String,vararg a:String?):String?=c.prepareStatement(sql).use{s->a.forEachIndexed{i,v->if(v==null)s.setNull(i+1,java.sql.Types.VARCHAR)else s.setString(i+1,v)};s.executeQuery().use{if(it.next())it.getString(1)else null}}
    private fun <T> tx(block:(Connection)->T):T=ds.connection.use{c->c.autoCommit=false;try{val v=block(c);c.commit();v}catch(e:Exception){c.rollback();throw e}}
    private fun audit(c:Connection,a:String,action:String,type:String,id:String){c.prepareStatement("INSERT INTO audit_event(id,actor_user_id,action,entity_type,entity_id) VALUES(?,?,?,?,?)").use{s->s.setString(1,UUID.randomUUID().toString());s.setString(2,a);s.setString(3,action);s.setString(4,type);s.setString(5,id);s.executeUpdate()}}
}

@kotlinx.serialization.Serializable data class SimpleQualityRecord(val id:String,val subjectId:String,val name:String,val detail:String,val status:String)
