package pe.gob.huata.ecolactea.core.model

import kotlinx.serialization.Serializable

@Serializable
enum class Permission { VIEW_SESSION, ADMIN_HOME, PLANT_HOME, COLLECTION_HOME, PROVIDER_HOME, MANAGE_USERS, VIEW_USERS, MANAGE_PROVIDERS, VIEW_PROVIDERS, MANAGE_ROUTES, VIEW_ROUTES, MANAGE_WORKDAYS, VIEW_WORKDAYS, MANAGE_CATALOG, VIEW_CATALOG, VIEW_REPORTS, VIEW_AUDIT, MANAGE_PARAMETERS, VIEW_PARAMETERS, MANAGE_COLLECTIONS, VIEW_COLLECTIONS, MANAGE_RECEPTION, VIEW_RECONCILIATION, RESOLVE_DISCREPANCIES, MANAGE_QUALITY, VIEW_QUALITY, MANAGE_COMMUNICATIONS, VIEW_COMMUNICATIONS, MANAGE_ATTENDANCE, VIEW_ATTENDANCE, MANAGE_MILK_PRICES, VIEW_MILK_PRICES, MANAGE_SETTLEMENTS, VIEW_SETTLEMENTS, MANAGE_PAYMENTS, VIEW_PAYMENTS, MANAGE_PRODUCTION, VIEW_PRODUCTION, MANAGE_SALES, VIEW_SALES, VIEW_FINANCIAL_REPORTS }

object Authorization {
    fun permissions(role: Role): Set<Permission> = setOf(Permission.VIEW_SESSION) + when (role) {
        Role.ADMINISTRADOR_GENERAL -> Permission.entries.toSet() - Permission.PROVIDER_HOME
        Role.PERSONAL_PLANTA -> setOf(Permission.PLANT_HOME, Permission.MANAGE_PROVIDERS, Permission.VIEW_PROVIDERS, Permission.MANAGE_ROUTES, Permission.VIEW_ROUTES, Permission.MANAGE_WORKDAYS, Permission.VIEW_WORKDAYS, Permission.MANAGE_CATALOG, Permission.VIEW_CATALOG, Permission.VIEW_REPORTS, Permission.VIEW_PARAMETERS, Permission.MANAGE_RECEPTION, Permission.VIEW_RECONCILIATION, Permission.RESOLVE_DISCREPANCIES, Permission.MANAGE_QUALITY, Permission.VIEW_QUALITY, Permission.MANAGE_COMMUNICATIONS, Permission.VIEW_COMMUNICATIONS, Permission.MANAGE_ATTENDANCE, Permission.VIEW_ATTENDANCE, Permission.VIEW_MILK_PRICES, Permission.MANAGE_SETTLEMENTS, Permission.VIEW_SETTLEMENTS, Permission.MANAGE_PAYMENTS, Permission.VIEW_PAYMENTS, Permission.MANAGE_PRODUCTION, Permission.VIEW_PRODUCTION, Permission.MANAGE_SALES, Permission.VIEW_SALES, Permission.VIEW_FINANCIAL_REPORTS)
        Role.ACOPIADOR -> setOf(Permission.COLLECTION_HOME, Permission.VIEW_REPORTS, Permission.VIEW_ROUTES, Permission.VIEW_WORKDAYS, Permission.VIEW_PROVIDERS, Permission.MANAGE_COLLECTIONS, Permission.VIEW_COLLECTIONS, Permission.MANAGE_MILK_PRICES, Permission.VIEW_MILK_PRICES)
        Role.PROVEEDOR -> setOf(Permission.PROVIDER_HOME, Permission.VIEW_QUALITY, Permission.VIEW_COMMUNICATIONS, Permission.VIEW_ATTENDANCE, Permission.VIEW_SETTLEMENTS, Permission.VIEW_PAYMENTS)
    }

    fun allows(user: AuthenticatedUser, permission: Permission): Boolean =
        permission in permissions(user.role)

    fun ownsProvider(user: AuthenticatedUser, providerId: String): Boolean =
        user.role == Role.PROVEEDOR && providerId.isNotBlank() && user.providerId == providerId
}
